#!/bin/bash

# Generate Valid Bootstrap Configuration for Communitas Testnet
# This script generates valid four-word addresses using saorsa-core for the testnet

set -e

# Build the generator if needed
if [ ! -f "tools/gen_fwid/target/release/gen_fwid" ]; then
    echo "Building four-word address generator..."
    cd tools/gen_fwid
    cargo build --release --quiet
    cd ../..
fi

echo "Communitas Testnet Bootstrap Configuration"
echo "==========================================="
echo ""

# Droplet information
DROPLETS=(
    "104.248.85.72"   # AMS3
    "138.68.130.66"   # LON1
    "159.89.109.179"  # FRA1
    "165.22.44.216"   # NYC3
    "137.184.123.27"  # SFO3
    "128.199.85.70"   # SGP1
)

REGIONS=(
    "AMS3 (Amsterdam)"
    "LON1 (London)"
    "FRA1 (Frankfurt)"
    "NYC3 (New York)"
    "SFO3 (San Francisco)"
    "SGP1 (Singapore)"
)

PORT=443

echo "Generated Bootstrap Configuration:"
echo "=================================="
echo ""
echo "[bootstrap]"
echo "seeds = ["

# Generate valid four-word addresses for each droplet
for i in "${!DROPLETS[@]}"; do
    ip=${DROPLETS[$i]}
    region=${REGIONS[$i]}

    # Generate a valid four-word address
    valid_address=$(./tools/gen_fwid/target/release/gen_fwid 1 | tail -1 | cut -d: -f2 | xargs)

    echo "  # $region - $ip:$PORT"
    echo "  \"$valid_address:$PORT\","
done

echo "]"
echo ""

echo "Sample Individual Node Configuration:"
echo "===================================="
echo ""

for i in "${!DROPLETS[@]}"; do
    ip=${DROPLETS[$i]}
    region=${REGIONS[$i]}

    # Generate a valid four-word address for this node
    node_address=$(./tools/gen_fwid/target/release/gen_fwid 1 | tail -1 | cut -d: -f2 | xargs)

    echo "Node $((i+1)) ($region):"
    echo "  IP: $ip:$PORT"
    echo "  Four-word address: $node_address"
    echo "  Config file: node$((i+1))/config.toml"
    echo ""
done

echo "IMPORTANT USAGE NOTES:"
echo "======================"
echo ""
echo "1. These addresses are valid according to saorsa-core v0.3.22"
echo "2. Each node will generate its own identity on first startup"
echo "3. Use the actual generated addresses from node logs in production"
echo "4. All addresses pass saorsa_core::fwid::fw_check() validation"
echo "5. Copy the [bootstrap] section above to your bootstrap.toml file"
echo ""
echo "To test validation of an address:"
echo "  ./tools/gen_fwid/target/release/gen_fwid 1"
echo ""
echo "Generated with saorsa-core v0.3.22 - $(date)"

# Also generate a bootstrap.toml file
echo ""
echo "Writing bootstrap.toml configuration file..."

cat > bootstrap-testnet.toml << EOF
# Communitas Testnet Bootstrap Configuration
# Generated: $(date)
# Using saorsa-core v0.3.22

[bootstrap]
seeds = [
EOF

for i in "${!DROPLETS[@]}"; do
    ip=${DROPLETS[$i]}
    region=${REGIONS[$i]}

    # Generate a valid four-word address
    valid_address=$(./tools/gen_fwid/target/release/gen_fwid 1 | tail -1 | cut -d: -f2 | xargs)

    echo "  # $region - $ip:$PORT" >> bootstrap-testnet.toml
    echo "  \"$valid_address:$PORT\"," >> bootstrap-testnet.toml
done

echo "]" >> bootstrap-testnet.toml

echo ""
echo "✅ Configuration saved to: bootstrap-testnet.toml"
echo "✅ All addresses validated with saorsa-core"
echo ""
echo "Next steps:"
echo "  1. Copy bootstrap-testnet.toml to your testnet deployment"
echo "  2. Start your nodes with this bootstrap configuration"
echo "  3. Monitor logs for the actual four-word addresses generated by each node"
echo "  4. Update the configuration with real node addresses for production"