import Foundation

/// Emoji category classification.
public enum EmojiCategory: String, CaseIterable, Identifiable, Sendable {
    case smileys = "Smileys"
    case people = "People"
    case nature = "Nature"
    case food = "Food"
    case travel = "Travel"
    case objects = "Objects"
    case symbols = "Symbols"
    case flags = "Flags"

    public var id: String { rawValue }

    /// SF Symbol icon representing this category in the picker UI.
    var systemImage: String {
        switch self {
        case .smileys: return "face.smiling"
        case .people: return "person.2"
        case .nature: return "leaf"
        case .food: return "fork.knife"
        case .travel: return "car"
        case .objects: return "lightbulb"
        case .symbols: return "number"
        case .flags: return "flag"
        }
    }
}

/// A single emoji with its name and category, used for searching and display.
public struct EmojiEntry: Sendable {
    public let emoji: String
    public let name: String
    public let category: EmojiCategory

    public init(emoji: String, name: String, category: EmojiCategory) {
        self.emoji = emoji
        self.name = name
        self.category = category
    }
}

/// Central emoji data source used by EmojiPicker and QuickReactionBar.
public enum EmojiData {

    // MARK: - Quick Reactions

    /// The 6 emojis shown in the quick-reaction bar on each message.
    public static let quickReactions = ["👍", "❤️", "😂", "😮", "😢", "🔥"]

    // MARK: - Full Emoji List

    /// All ~170 common emojis across all categories.
    public static let allEmojis: [EmojiEntry] = smileys + people + nature + food + travel + objects + symbols + flags

    // MARK: - Search

    /// Case-insensitive name match across all emojis.
    public static func search(_ query: String) -> [EmojiEntry] {
        let q = query.lowercased()
        return allEmojis.filter { $0.name.lowercased().contains(q) }
    }

    /// Return all emojis in a given category.
    public static func byCategory(_ category: EmojiCategory) -> [EmojiEntry] {
        allEmojis.filter { $0.category == category }
    }

    // MARK: - Category Data

    private static let smileys: [EmojiEntry] = [
        EmojiEntry(emoji: "😀", name: "grinning face", category: .smileys),
        EmojiEntry(emoji: "😃", name: "grinning face with big eyes", category: .smileys),
        EmojiEntry(emoji: "😄", name: "grinning face with smiling eyes", category: .smileys),
        EmojiEntry(emoji: "😁", name: "beaming face with smiling eyes", category: .smileys),
        EmojiEntry(emoji: "😆", name: "grinning squinting face", category: .smileys),
        EmojiEntry(emoji: "😅", name: "grinning face with sweat", category: .smileys),
        EmojiEntry(emoji: "🤣", name: "rolling on the floor laughing", category: .smileys),
        EmojiEntry(emoji: "😂", name: "face with tears of joy", category: .smileys),
        EmojiEntry(emoji: "🙂", name: "slightly smiling face", category: .smileys),
        EmojiEntry(emoji: "🙃", name: "upside down face", category: .smileys),
        EmojiEntry(emoji: "😉", name: "winking face", category: .smileys),
        EmojiEntry(emoji: "😊", name: "smiling face with smiling eyes", category: .smileys),
        EmojiEntry(emoji: "😇", name: "smiling face with halo", category: .smileys),
        EmojiEntry(emoji: "🥰", name: "smiling face with hearts", category: .smileys),
        EmojiEntry(emoji: "😍", name: "smiling face with heart eyes", category: .smileys),
        EmojiEntry(emoji: "🤩", name: "star struck", category: .smileys),
        EmojiEntry(emoji: "😘", name: "face blowing a kiss", category: .smileys),
        EmojiEntry(emoji: "😗", name: "kissing face", category: .smileys),
        EmojiEntry(emoji: "😚", name: "kissing face with closed eyes", category: .smileys),
        EmojiEntry(emoji: "😙", name: "kissing face with smiling eyes", category: .smileys),
        EmojiEntry(emoji: "🥲", name: "smiling face with tear", category: .smileys),
        EmojiEntry(emoji: "😋", name: "face savoring food", category: .smileys),
        EmojiEntry(emoji: "😛", name: "face with tongue", category: .smileys),
        EmojiEntry(emoji: "😜", name: "winking face with tongue", category: .smileys),
        EmojiEntry(emoji: "🤪", name: "zany face", category: .smileys),
        EmojiEntry(emoji: "😝", name: "squinting face with tongue", category: .smileys),
        EmojiEntry(emoji: "🤑", name: "money mouth face", category: .smileys),
        EmojiEntry(emoji: "🤗", name: "smiling face with open hands", category: .smileys),
        EmojiEntry(emoji: "🤭", name: "face with hand over mouth", category: .smileys),
        EmojiEntry(emoji: "🤫", name: "shushing face", category: .smileys),
        EmojiEntry(emoji: "🤔", name: "thinking face", category: .smileys),
        EmojiEntry(emoji: "🤐", name: "zipper mouth face", category: .smileys),
        EmojiEntry(emoji: "🤨", name: "face with raised eyebrow", category: .smileys),
        EmojiEntry(emoji: "😐", name: "neutral face", category: .smileys),
        EmojiEntry(emoji: "😑", name: "expressionless face", category: .smileys),
        EmojiEntry(emoji: "😶", name: "face without mouth", category: .smileys),
        EmojiEntry(emoji: "😏", name: "smirking face", category: .smileys),
        EmojiEntry(emoji: "😒", name: "unamused face", category: .smileys),
        EmojiEntry(emoji: "🙄", name: "face with rolling eyes", category: .smileys),
        EmojiEntry(emoji: "😬", name: "grimacing face", category: .smileys),
        EmojiEntry(emoji: "😮", name: "face with open mouth", category: .smileys),
        EmojiEntry(emoji: "😯", name: "hushed face", category: .smileys),
        EmojiEntry(emoji: "😲", name: "astonished face", category: .smileys),
        EmojiEntry(emoji: "😳", name: "flushed face", category: .smileys),
        EmojiEntry(emoji: "🥺", name: "pleading face", category: .smileys),
        EmojiEntry(emoji: "😦", name: "frowning face with open mouth", category: .smileys),
        EmojiEntry(emoji: "😧", name: "anguished face", category: .smileys),
        EmojiEntry(emoji: "😨", name: "fearful face", category: .smileys),
        EmojiEntry(emoji: "😰", name: "anxious face with sweat", category: .smileys),
        EmojiEntry(emoji: "😥", name: "sad but relieved face", category: .smileys),
        EmojiEntry(emoji: "😢", name: "crying face", category: .smileys),
        EmojiEntry(emoji: "😭", name: "loudly crying face", category: .smileys),
        EmojiEntry(emoji: "😱", name: "face screaming in fear", category: .smileys),
        EmojiEntry(emoji: "😖", name: "confounded face", category: .smileys),
        EmojiEntry(emoji: "😣", name: "persevering face", category: .smileys),
        EmojiEntry(emoji: "😞", name: "disappointed face", category: .smileys),
        EmojiEntry(emoji: "😓", name: "downcast face with sweat", category: .smileys),
        EmojiEntry(emoji: "😩", name: "weary face", category: .smileys),
        EmojiEntry(emoji: "😫", name: "tired face", category: .smileys),
        EmojiEntry(emoji: "🥱", name: "yawning face", category: .smileys),
        EmojiEntry(emoji: "😤", name: "face with steam from nose", category: .smileys),
        EmojiEntry(emoji: "😡", name: "enraged face", category: .smileys),
        EmojiEntry(emoji: "😠", name: "angry face", category: .smileys),
        EmojiEntry(emoji: "🤬", name: "face with symbols on mouth", category: .smileys),
        EmojiEntry(emoji: "😈", name: "smiling face with horns", category: .smileys),
        EmojiEntry(emoji: "👿", name: "angry face with horns", category: .smileys),
        EmojiEntry(emoji: "💀", name: "skull", category: .smileys),
        EmojiEntry(emoji: "☠️", name: "skull and crossbones", category: .smileys),
        EmojiEntry(emoji: "💩", name: "pile of poo", category: .smileys),
        EmojiEntry(emoji: "🤡", name: "clown face", category: .smileys),
        EmojiEntry(emoji: "👹", name: "ogre", category: .smileys),
        EmojiEntry(emoji: "👺", name: "goblin", category: .smileys),
        EmojiEntry(emoji: "👻", name: "ghost", category: .smileys),
        EmojiEntry(emoji: "👽", name: "alien", category: .smileys),
        EmojiEntry(emoji: "👾", name: "alien monster", category: .smileys),
        EmojiEntry(emoji: "🤖", name: "robot", category: .smileys),
        EmojiEntry(emoji: "😺", name: "grinning cat", category: .smileys),
        EmojiEntry(emoji: "😸", name: "grinning cat with smiling eyes", category: .smileys),
        EmojiEntry(emoji: "🙈", name: "see no evil monkey", category: .smileys),
        EmojiEntry(emoji: "🙉", name: "hear no evil monkey", category: .smileys),
        EmojiEntry(emoji: "🙊", name: "speak no evil monkey", category: .smileys),
    ]

    private static let people: [EmojiEntry] = [
        EmojiEntry(emoji: "👋", name: "waving hand", category: .people),
        EmojiEntry(emoji: "🤚", name: "raised back of hand", category: .people),
        EmojiEntry(emoji: "✋", name: "raised hand", category: .people),
        EmojiEntry(emoji: "🖐️", name: "hand with fingers splayed", category: .people),
        EmojiEntry(emoji: "👌", name: "ok hand", category: .people),
        EmojiEntry(emoji: "🤌", name: "pinched fingers", category: .people),
        EmojiEntry(emoji: "✌️", name: "victory hand", category: .people),
        EmojiEntry(emoji: "🤞", name: "crossed fingers", category: .people),
        EmojiEntry(emoji: "🤟", name: "love you gesture", category: .people),
        EmojiEntry(emoji: "🤘", name: "sign of the horns", category: .people),
        EmojiEntry(emoji: "🤙", name: "call me hand", category: .people),
        EmojiEntry(emoji: "👈", name: "backhand index pointing left", category: .people),
        EmojiEntry(emoji: "👉", name: "backhand index pointing right", category: .people),
        EmojiEntry(emoji: "👆", name: "backhand index pointing up", category: .people),
        EmojiEntry(emoji: "👇", name: "backhand index pointing down", category: .people),
        EmojiEntry(emoji: "☝️", name: "index pointing up", category: .people),
        EmojiEntry(emoji: "👍", name: "thumbs up", category: .people),
        EmojiEntry(emoji: "👎", name: "thumbs down", category: .people),
        EmojiEntry(emoji: "✊", name: "raised fist", category: .people),
        EmojiEntry(emoji: "👊", name: "oncoming fist", category: .people),
        EmojiEntry(emoji: "🤛", name: "left-facing fist", category: .people),
        EmojiEntry(emoji: "🤜", name: "right-facing fist", category: .people),
        EmojiEntry(emoji: "👏", name: "clapping hands", category: .people),
        EmojiEntry(emoji: "🙌", name: "raising hands", category: .people),
        EmojiEntry(emoji: "👐", name: "open hands", category: .people),
        EmojiEntry(emoji: "🤲", name: "palms up together", category: .people),
        EmojiEntry(emoji: "🤝", name: "handshake", category: .people),
        EmojiEntry(emoji: "🙏", name: "folded hands", category: .people),
        EmojiEntry(emoji: "✍️", name: "writing hand", category: .people),
        EmojiEntry(emoji: "💪", name: "flexed biceps", category: .people),
        EmojiEntry(emoji: "🦾", name: "mechanical arm", category: .people),
        EmojiEntry(emoji: "👀", name: "eyes", category: .people),
        EmojiEntry(emoji: "👁️", name: "eye", category: .people),
        EmojiEntry(emoji: "👶", name: "baby", category: .people),
        EmojiEntry(emoji: "🧒", name: "child", category: .people),
        EmojiEntry(emoji: "👦", name: "boy", category: .people),
        EmojiEntry(emoji: "👧", name: "girl", category: .people),
        EmojiEntry(emoji: "🧑", name: "person", category: .people),
        EmojiEntry(emoji: "👨", name: "man", category: .people),
        EmojiEntry(emoji: "👩", name: "woman", category: .people),
        EmojiEntry(emoji: "🧓", name: "older person", category: .people),
        EmojiEntry(emoji: "👴", name: "old man", category: .people),
        EmojiEntry(emoji: "👵", name: "old woman", category: .people),
        EmojiEntry(emoji: "🎅", name: "santa claus", category: .people),
        EmojiEntry(emoji: "🤶", name: "mrs claus", category: .people),
        EmojiEntry(emoji: "🧑‍💻", name: "technologist", category: .people),
        EmojiEntry(emoji: "👮", name: "police officer", category: .people),
        EmojiEntry(emoji: "👷", name: "construction worker", category: .people),
        EmojiEntry(emoji: "💂", name: "guard", category: .people),
        EmojiEntry(emoji: "🕵️", name: "detective", category: .people),
        EmojiEntry(emoji: "👸", name: "princess", category: .people),
        EmojiEntry(emoji: "🤴", name: "prince", category: .people),
    ]

    private static let nature: [EmojiEntry] = [
        EmojiEntry(emoji: "🐶", name: "dog face", category: .nature),
        EmojiEntry(emoji: "🐱", name: "cat face", category: .nature),
        EmojiEntry(emoji: "🐭", name: "mouse face", category: .nature),
        EmojiEntry(emoji: "🐹", name: "hamster", category: .nature),
        EmojiEntry(emoji: "🐰", name: "rabbit face", category: .nature),
        EmojiEntry(emoji: "🦊", name: "fox", category: .nature),
        EmojiEntry(emoji: "🐻", name: "bear", category: .nature),
        EmojiEntry(emoji: "🐼", name: "panda", category: .nature),
        EmojiEntry(emoji: "🐨", name: "koala", category: .nature),
        EmojiEntry(emoji: "🐯", name: "tiger face", category: .nature),
        EmojiEntry(emoji: "🦁", name: "lion", category: .nature),
        EmojiEntry(emoji: "🐮", name: "cow face", category: .nature),
        EmojiEntry(emoji: "🐷", name: "pig face", category: .nature),
        EmojiEntry(emoji: "🐸", name: "frog", category: .nature),
        EmojiEntry(emoji: "🐵", name: "monkey face", category: .nature),
        EmojiEntry(emoji: "🐔", name: "chicken", category: .nature),
        EmojiEntry(emoji: "🐧", name: "penguin", category: .nature),
        EmojiEntry(emoji: "🐦", name: "bird", category: .nature),
        EmojiEntry(emoji: "🦆", name: "duck", category: .nature),
        EmojiEntry(emoji: "🦅", name: "eagle", category: .nature),
        EmojiEntry(emoji: "🦉", name: "owl", category: .nature),
        EmojiEntry(emoji: "🦋", name: "butterfly", category: .nature),
        EmojiEntry(emoji: "🐛", name: "bug", category: .nature),
        EmojiEntry(emoji: "🐝", name: "honeybee", category: .nature),
        EmojiEntry(emoji: "🐌", name: "snail", category: .nature),
        EmojiEntry(emoji: "🦀", name: "crab", category: .nature),
        EmojiEntry(emoji: "🐠", name: "tropical fish", category: .nature),
        EmojiEntry(emoji: "🐳", name: "spouting whale", category: .nature),
        EmojiEntry(emoji: "🦈", name: "shark", category: .nature),
        EmojiEntry(emoji: "🐊", name: "crocodile", category: .nature),
        EmojiEntry(emoji: "🌸", name: "cherry blossom", category: .nature),
        EmojiEntry(emoji: "🌺", name: "hibiscus", category: .nature),
        EmojiEntry(emoji: "🌻", name: "sunflower", category: .nature),
        EmojiEntry(emoji: "🌹", name: "rose", category: .nature),
        EmojiEntry(emoji: "🍀", name: "four leaf clover", category: .nature),
        EmojiEntry(emoji: "🌿", name: "herb", category: .nature),
        EmojiEntry(emoji: "🍃", name: "leaf fluttering in wind", category: .nature),
        EmojiEntry(emoji: "🍂", name: "fallen leaf", category: .nature),
        EmojiEntry(emoji: "🍁", name: "maple leaf", category: .nature),
        EmojiEntry(emoji: "🌵", name: "cactus", category: .nature),
        EmojiEntry(emoji: "🌴", name: "palm tree", category: .nature),
        EmojiEntry(emoji: "🌲", name: "evergreen tree", category: .nature),
        EmojiEntry(emoji: "⭐", name: "star", category: .nature),
        EmojiEntry(emoji: "🌟", name: "glowing star", category: .nature),
        EmojiEntry(emoji: "✨", name: "sparkles", category: .nature),
        EmojiEntry(emoji: "☀️", name: "sun", category: .nature),
        EmojiEntry(emoji: "🌈", name: "rainbow", category: .nature),
        EmojiEntry(emoji: "⛅", name: "sun behind cloud", category: .nature),
        EmojiEntry(emoji: "🌊", name: "water wave", category: .nature),
        EmojiEntry(emoji: "❄️", name: "snowflake", category: .nature),
        EmojiEntry(emoji: "🌙", name: "crescent moon", category: .nature),
        EmojiEntry(emoji: "🌍", name: "globe europe africa", category: .nature),
    ]

    private static let food: [EmojiEntry] = [
        EmojiEntry(emoji: "🍎", name: "red apple", category: .food),
        EmojiEntry(emoji: "🍊", name: "tangerine", category: .food),
        EmojiEntry(emoji: "🍋", name: "lemon", category: .food),
        EmojiEntry(emoji: "🍇", name: "grapes", category: .food),
        EmojiEntry(emoji: "🍓", name: "strawberry", category: .food),
        EmojiEntry(emoji: "🍒", name: "cherries", category: .food),
        EmojiEntry(emoji: "🍑", name: "peach", category: .food),
        EmojiEntry(emoji: "🥭", name: "mango", category: .food),
        EmojiEntry(emoji: "🍍", name: "pineapple", category: .food),
        EmojiEntry(emoji: "🥥", name: "coconut", category: .food),
        EmojiEntry(emoji: "🥑", name: "avocado", category: .food),
        EmojiEntry(emoji: "🍆", name: "eggplant", category: .food),
        EmojiEntry(emoji: "🥕", name: "carrot", category: .food),
        EmojiEntry(emoji: "🌽", name: "ear of corn", category: .food),
        EmojiEntry(emoji: "🌶️", name: "hot pepper", category: .food),
        EmojiEntry(emoji: "🥦", name: "broccoli", category: .food),
        EmojiEntry(emoji: "🧄", name: "garlic", category: .food),
        EmojiEntry(emoji: "🧅", name: "onion", category: .food),
        EmojiEntry(emoji: "🍞", name: "bread", category: .food),
        EmojiEntry(emoji: "🥐", name: "croissant", category: .food),
        EmojiEntry(emoji: "🥨", name: "pretzel", category: .food),
        EmojiEntry(emoji: "🧀", name: "cheese wedge", category: .food),
        EmojiEntry(emoji: "🥚", name: "egg", category: .food),
        EmojiEntry(emoji: "🍳", name: "cooking", category: .food),
        EmojiEntry(emoji: "🥞", name: "pancakes", category: .food),
        EmojiEntry(emoji: "🧇", name: "waffle", category: .food),
        EmojiEntry(emoji: "🍗", name: "poultry leg", category: .food),
        EmojiEntry(emoji: "🍔", name: "hamburger", category: .food),
        EmojiEntry(emoji: "🍟", name: "french fries", category: .food),
        EmojiEntry(emoji: "🍕", name: "pizza", category: .food),
        EmojiEntry(emoji: "🌮", name: "taco", category: .food),
        EmojiEntry(emoji: "🌯", name: "burrito", category: .food),
        EmojiEntry(emoji: "🍜", name: "steaming bowl", category: .food),
        EmojiEntry(emoji: "🍣", name: "sushi", category: .food),
        EmojiEntry(emoji: "🍩", name: "doughnut", category: .food),
        EmojiEntry(emoji: "🎂", name: "birthday cake", category: .food),
        EmojiEntry(emoji: "🍦", name: "soft ice cream", category: .food),
        EmojiEntry(emoji: "🍫", name: "chocolate bar", category: .food),
        EmojiEntry(emoji: "🍬", name: "candy", category: .food),
        EmojiEntry(emoji: "🍭", name: "lollipop", category: .food),
        EmojiEntry(emoji: "☕", name: "hot beverage", category: .food),
        EmojiEntry(emoji: "🍵", name: "teacup without handle", category: .food),
        EmojiEntry(emoji: "🧃", name: "beverage box", category: .food),
        EmojiEntry(emoji: "🥤", name: "cup with straw", category: .food),
        EmojiEntry(emoji: "🍺", name: "beer mug", category: .food),
        EmojiEntry(emoji: "🍷", name: "wine glass", category: .food),
        EmojiEntry(emoji: "🥂", name: "clinking glasses", category: .food),
        EmojiEntry(emoji: "🍸", name: "cocktail glass", category: .food),
    ]

    private static let travel: [EmojiEntry] = [
        EmojiEntry(emoji: "🚗", name: "automobile", category: .travel),
        EmojiEntry(emoji: "🚕", name: "taxi", category: .travel),
        EmojiEntry(emoji: "🚙", name: "sport utility vehicle", category: .travel),
        EmojiEntry(emoji: "🚌", name: "bus", category: .travel),
        EmojiEntry(emoji: "🏎️", name: "racing car", category: .travel),
        EmojiEntry(emoji: "🚑", name: "ambulance", category: .travel),
        EmojiEntry(emoji: "🚒", name: "fire engine", category: .travel),
        EmojiEntry(emoji: "✈️", name: "airplane", category: .travel),
        EmojiEntry(emoji: "🚀", name: "rocket", category: .travel),
        EmojiEntry(emoji: "🛸", name: "flying saucer", category: .travel),
        EmojiEntry(emoji: "🚁", name: "helicopter", category: .travel),
        EmojiEntry(emoji: "⛵", name: "sailboat", category: .travel),
        EmojiEntry(emoji: "🚢", name: "ship", category: .travel),
        EmojiEntry(emoji: "🏖️", name: "beach with umbrella", category: .travel),
        EmojiEntry(emoji: "🏔️", name: "snow capped mountain", category: .travel),
        EmojiEntry(emoji: "🗻", name: "mount fuji", category: .travel),
        EmojiEntry(emoji: "🏕️", name: "camping", category: .travel),
        EmojiEntry(emoji: "🏝️", name: "desert island", category: .travel),
        EmojiEntry(emoji: "🏟️", name: "stadium", category: .travel),
        EmojiEntry(emoji: "🗼", name: "tokyo tower", category: .travel),
        EmojiEntry(emoji: "🗽", name: "statue of liberty", category: .travel),
        EmojiEntry(emoji: "🏰", name: "european castle", category: .travel),
        EmojiEntry(emoji: "🌆", name: "cityscape at dusk", category: .travel),
        EmojiEntry(emoji: "🌉", name: "bridge at night", category: .travel),
        EmojiEntry(emoji: "🌐", name: "globe with meridians", category: .travel),
        EmojiEntry(emoji: "🗺️", name: "world map", category: .travel),
        EmojiEntry(emoji: "🧭", name: "compass", category: .travel),
        EmojiEntry(emoji: "🏖️", name: "beach with umbrella", category: .travel),
        EmojiEntry(emoji: "⛱️", name: "umbrella on ground", category: .travel),
        EmojiEntry(emoji: "🛤️", name: "railway track", category: .travel),
    ]

    private static let objects: [EmojiEntry] = [
        EmojiEntry(emoji: "⌚", name: "watch", category: .objects),
        EmojiEntry(emoji: "📱", name: "mobile phone", category: .objects),
        EmojiEntry(emoji: "💻", name: "laptop", category: .objects),
        EmojiEntry(emoji: "⌨️", name: "keyboard", category: .objects),
        EmojiEntry(emoji: "🖨️", name: "printer", category: .objects),
        EmojiEntry(emoji: "📷", name: "camera", category: .objects),
        EmojiEntry(emoji: "📹", name: "video camera", category: .objects),
        EmojiEntry(emoji: "📞", name: "telephone receiver", category: .objects),
        EmojiEntry(emoji: "📺", name: "television", category: .objects),
        EmojiEntry(emoji: "📻", name: "radio", category: .objects),
        EmojiEntry(emoji: "🔋", name: "battery", category: .objects),
        EmojiEntry(emoji: "💡", name: "light bulb", category: .objects),
        EmojiEntry(emoji: "🔦", name: "flashlight", category: .objects),
        EmojiEntry(emoji: "🕯️", name: "candle", category: .objects),
        EmojiEntry(emoji: "🛒", name: "shopping cart", category: .objects),
        EmojiEntry(emoji: "🛍️", name: "shopping bags", category: .objects),
        EmojiEntry(emoji: "🎁", name: "wrapped gift", category: .objects),
        EmojiEntry(emoji: "🎈", name: "balloon", category: .objects),
        EmojiEntry(emoji: "🎉", name: "party popper", category: .objects),
        EmojiEntry(emoji: "🎊", name: "confetti ball", category: .objects),
        EmojiEntry(emoji: "🎭", name: "performing arts", category: .objects),
        EmojiEntry(emoji: "🎨", name: "artist palette", category: .objects),
        EmojiEntry(emoji: "🎬", name: "clapper board", category: .objects),
        EmojiEntry(emoji: "🎤", name: "microphone", category: .objects),
        EmojiEntry(emoji: "🎵", name: "musical note", category: .objects),
        EmojiEntry(emoji: "🎶", name: "musical notes", category: .objects),
        EmojiEntry(emoji: "🎸", name: "guitar", category: .objects),
        EmojiEntry(emoji: "🎹", name: "musical keyboard", category: .objects),
        EmojiEntry(emoji: "🥁", name: "drum", category: .objects),
        EmojiEntry(emoji: "📚", name: "books", category: .objects),
        EmojiEntry(emoji: "📖", name: "open book", category: .objects),
        EmojiEntry(emoji: "📝", name: "memo", category: .objects),
        EmojiEntry(emoji: "✏️", name: "pencil", category: .objects),
        EmojiEntry(emoji: "🔍", name: "magnifying glass tilted left", category: .objects),
        EmojiEntry(emoji: "🔑", name: "key", category: .objects),
        EmojiEntry(emoji: "🔒", name: "locked", category: .objects),
        EmojiEntry(emoji: "🔓", name: "unlocked", category: .objects),
        EmojiEntry(emoji: "🔨", name: "hammer", category: .objects),
        EmojiEntry(emoji: "⚙️", name: "gear", category: .objects),
        EmojiEntry(emoji: "🧰", name: "toolbox", category: .objects),
        EmojiEntry(emoji: "🧲", name: "magnet", category: .objects),
        EmojiEntry(emoji: "🏆", name: "trophy", category: .objects),
        EmojiEntry(emoji: "🥇", name: "first place medal", category: .objects),
        EmojiEntry(emoji: "🎯", name: "bullseye", category: .objects),
        EmojiEntry(emoji: "🎲", name: "game die", category: .objects),
        EmojiEntry(emoji: "♟️", name: "chess pawn", category: .objects),
        EmojiEntry(emoji: "🃏", name: "joker", category: .objects),
        EmojiEntry(emoji: "🧩", name: "puzzle piece", category: .objects),
        EmojiEntry(emoji: "🪄", name: "magic wand", category: .objects),
        EmojiEntry(emoji: "🔥", name: "fire", category: .objects),
        EmojiEntry(emoji: "💊", name: "pill", category: .objects),
        EmojiEntry(emoji: "🩺", name: "stethoscope", category: .objects),
    ]

    private static let symbols: [EmojiEntry] = [
        EmojiEntry(emoji: "❤️", name: "red heart", category: .symbols),
        EmojiEntry(emoji: "🧡", name: "orange heart", category: .symbols),
        EmojiEntry(emoji: "💛", name: "yellow heart", category: .symbols),
        EmojiEntry(emoji: "💚", name: "green heart", category: .symbols),
        EmojiEntry(emoji: "💙", name: "blue heart", category: .symbols),
        EmojiEntry(emoji: "💜", name: "purple heart", category: .symbols),
        EmojiEntry(emoji: "🖤", name: "black heart", category: .symbols),
        EmojiEntry(emoji: "🤍", name: "white heart", category: .symbols),
        EmojiEntry(emoji: "🤎", name: "brown heart", category: .symbols),
        EmojiEntry(emoji: "💔", name: "broken heart", category: .symbols),
        EmojiEntry(emoji: "❣️", name: "heart exclamation", category: .symbols),
        EmojiEntry(emoji: "💕", name: "two hearts", category: .symbols),
        EmojiEntry(emoji: "💞", name: "revolving hearts", category: .symbols),
        EmojiEntry(emoji: "💓", name: "beating heart", category: .symbols),
        EmojiEntry(emoji: "💗", name: "growing heart", category: .symbols),
        EmojiEntry(emoji: "💖", name: "sparkling heart", category: .symbols),
        EmojiEntry(emoji: "💘", name: "heart with arrow", category: .symbols),
        EmojiEntry(emoji: "💝", name: "heart with ribbon", category: .symbols),
        EmojiEntry(emoji: "💯", name: "hundred points", category: .symbols),
        EmojiEntry(emoji: "💢", name: "anger symbol", category: .symbols),
        EmojiEntry(emoji: "💥", name: "collision", category: .symbols),
        EmojiEntry(emoji: "💫", name: "dizzy", category: .symbols),
        EmojiEntry(emoji: "💦", name: "sweat droplets", category: .symbols),
        EmojiEntry(emoji: "💨", name: "dashing away", category: .symbols),
        EmojiEntry(emoji: "🕳️", name: "hole", category: .symbols),
        EmojiEntry(emoji: "💬", name: "speech balloon", category: .symbols),
        EmojiEntry(emoji: "💭", name: "thought balloon", category: .symbols),
        EmojiEntry(emoji: "🔔", name: "bell", category: .symbols),
        EmojiEntry(emoji: "🔕", name: "bell with slash", category: .symbols),
        EmojiEntry(emoji: "🎵", name: "musical note", category: .symbols),
        EmojiEntry(emoji: "⚡", name: "high voltage", category: .symbols),
        EmojiEntry(emoji: "🌀", name: "cyclone", category: .symbols),
        EmojiEntry(emoji: "♻️", name: "recycling symbol", category: .symbols),
        EmojiEntry(emoji: "✅", name: "check mark button", category: .symbols),
        EmojiEntry(emoji: "❌", name: "cross mark", category: .symbols),
        EmojiEntry(emoji: "❓", name: "question mark", category: .symbols),
        EmojiEntry(emoji: "❗", name: "exclamation mark", category: .symbols),
        EmojiEntry(emoji: "💤", name: "zzz", category: .symbols),
        EmojiEntry(emoji: "🆒", name: "cool button", category: .symbols),
        EmojiEntry(emoji: "🆕", name: "new button", category: .symbols),
        EmojiEntry(emoji: "🔞", name: "no one under eighteen", category: .symbols),
        EmojiEntry(emoji: "⭕", name: "hollow red circle", category: .symbols),
        EmojiEntry(emoji: "🔴", name: "red circle", category: .symbols),
        EmojiEntry(emoji: "🟠", name: "orange circle", category: .symbols),
        EmojiEntry(emoji: "🟡", name: "yellow circle", category: .symbols),
        EmojiEntry(emoji: "🟢", name: "green circle", category: .symbols),
        EmojiEntry(emoji: "🔵", name: "blue circle", category: .symbols),
        EmojiEntry(emoji: "🟣", name: "purple circle", category: .symbols),
    ]

    private static let flags: [EmojiEntry] = [
        EmojiEntry(emoji: "🏁", name: "chequered flag", category: .flags),
        EmojiEntry(emoji: "🚩", name: "triangular flag", category: .flags),
        EmojiEntry(emoji: "🎌", name: "crossed flags", category: .flags),
        EmojiEntry(emoji: "🏴", name: "black flag", category: .flags),
        EmojiEntry(emoji: "🏳️", name: "white flag", category: .flags),
        EmojiEntry(emoji: "🏳️‍🌈", name: "rainbow flag", category: .flags),
        EmojiEntry(emoji: "🇺🇸", name: "flag united states", category: .flags),
        EmojiEntry(emoji: "🇬🇧", name: "flag united kingdom", category: .flags),
        EmojiEntry(emoji: "🇨🇦", name: "flag canada", category: .flags),
        EmojiEntry(emoji: "🇦🇺", name: "flag australia", category: .flags),
        EmojiEntry(emoji: "🇩🇪", name: "flag germany", category: .flags),
        EmojiEntry(emoji: "🇫🇷", name: "flag france", category: .flags),
        EmojiEntry(emoji: "🇯🇵", name: "flag japan", category: .flags),
        EmojiEntry(emoji: "🇧🇷", name: "flag brazil", category: .flags),
        EmojiEntry(emoji: "🇮🇳", name: "flag india", category: .flags),
        EmojiEntry(emoji: "🇨🇳", name: "flag china", category: .flags),
        EmojiEntry(emoji: "🇰🇷", name: "flag south korea", category: .flags),
        EmojiEntry(emoji: "🇲🇽", name: "flag mexico", category: .flags),
        EmojiEntry(emoji: "🇮🇹", name: "flag italy", category: .flags),
        EmojiEntry(emoji: "🇪🇸", name: "flag spain", category: .flags),
        EmojiEntry(emoji: "🇳🇱", name: "flag netherlands", category: .flags),
        EmojiEntry(emoji: "🇷🇺", name: "flag russia", category: .flags),
        EmojiEntry(emoji: "🇸🇪", name: "flag sweden", category: .flags),
        EmojiEntry(emoji: "🇳🇴", name: "flag norway", category: .flags),
        EmojiEntry(emoji: "🇫🇮", name: "flag finland", category: .flags),
        EmojiEntry(emoji: "🇩🇰", name: "flag denmark", category: .flags),
        EmojiEntry(emoji: "🇨🇭", name: "flag switzerland", category: .flags),
        EmojiEntry(emoji: "🇵🇹", name: "flag portugal", category: .flags),
        EmojiEntry(emoji: "🇵🇱", name: "flag poland", category: .flags),
        EmojiEntry(emoji: "🇺🇦", name: "flag ukraine", category: .flags),
        EmojiEntry(emoji: "🇸🇬", name: "flag singapore", category: .flags),
        EmojiEntry(emoji: "🇳🇿", name: "flag new zealand", category: .flags),
        EmojiEntry(emoji: "🇮🇪", name: "flag ireland", category: .flags),
        EmojiEntry(emoji: "🇬🇷", name: "flag greece", category: .flags),
        EmojiEntry(emoji: "🇿🇦", name: "flag south africa", category: .flags),
        EmojiEntry(emoji: "🇦🇷", name: "flag argentina", category: .flags),
    ]
}
