// Copyright (c) 2025 Saorsa Labs Limited
//
// Licensed under the AGPL-3.0 license

//! Generated Test Stubs for Untested MCP Tools
//!
//! These stubs were auto-generated and should be reviewed and customized.
//! Move completed tests to appropriate test files.
//!
//! Generated by: communitas-mcp/tests/generator

#![allow(dead_code)]
#![cfg(test)]

mod harness;

use harness::{McpTestClient, ToolAssert};
use serde_json::json;

// === CALL ===

/// Test: get_call_participants - Get call participants
/// Category: call
#[tokio::test]
async fn test_get_call_participants() {
    let client = McpTestClient::new().await;

    // This tool requires an active call which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_call_participants",
            json!({
                "call_id": "non-existent-call"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: get_call_quality - Get call quality metrics
/// Category: call
#[tokio::test]
async fn test_get_call_quality() {
    let client = McpTestClient::new().await;

    // Returns quality metrics from current snapshot (defaults when no call)
    let result = client.call_tool("get_call_quality", json!({})).await;

    result
        .assert_success()
        .assert_has("quality")
        .assert_has("latency_ms")
        .assert_has("packet_loss_percent")
        .assert_has("jitter_ms")
        .assert_has("audio_bitrate_kbps")
        .assert_has("video_bitrate_kbps")
        .assert_has("is_in_call")
        .assert_bool_eq("is_in_call", false);
}

/// Test: get_call_status - Get call status
/// Category: call
#[tokio::test]
async fn test_get_call_status() {
    let client = McpTestClient::new().await;

    // This tool requires an active call which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_call_status",
            json!({
                "call_id": "non-existent-call"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: list_active_calls - List active calls
/// Category: call
#[tokio::test]
async fn test_list_active_calls() {
    let client = McpTestClient::new().await;

    // CallService may not be fully available in test environment
    let result = client.call_tool("list_active_calls", json!({})).await;

    result.assert_error();
}

/// Test: list_media_devices - List media devices
/// Category: call
#[tokio::test]
async fn test_list_media_devices() {
    let client = McpTestClient::new().await;

    // Device API may not be available in test environment
    let result = client.call_tool("list_media_devices", json!({})).await;

    result.assert_error();
}

/// Test: toggle_mute - Toggle microphone mute
/// Category: call
#[tokio::test]
async fn test_toggle_mute() {
    let client = McpTestClient::new().await;

    // Requires an active call which doesn't exist in test environment
    let result = client
        .call_tool(
            "toggle_mute",
            json!({
                "call_id": "non-existent-call"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: toggle_video - Toggle video
/// Category: call
#[tokio::test]
async fn test_toggle_video() {
    let client = McpTestClient::new().await;

    // Requires an active call which doesn't exist in test environment
    let result = client
        .call_tool(
            "toggle_video",
            json!({
                "call_id": "non-existent-call"
            }),
        )
        .await;

    result.assert_error();
}

// === CALL_HISTORY ===

/// Test: acknowledge_missed_call - Acknowledge missed call
/// Category: call_history
#[tokio::test]
async fn test_acknowledge_missed_call() {
    let client = McpTestClient::new().await;

    // Acknowledging a call succeeds even if the call doesn't exist
    let result = client
        .call_tool(
            "acknowledge_missed_call",
            json!({
                "call_id": "test-call-123"
            }),
        )
        .await;

    result
        .assert_success()
        .assert_bool_eq("success", true)
        .assert_has("call_id")
        .assert_has("message");
}

/// Test: get_call_history - Get call history
/// Category: call_history
#[tokio::test]
async fn test_get_call_history() {
    let client = McpTestClient::new().await;

    // Returns call history (empty in test environment)
    let result = client
        .call_tool("get_call_history", json!({"limit": 20}))
        .await;

    result
        .assert_success()
        .assert_has("total")
        .assert_num_gte("total", 0)
        .assert_has("returned")
        .assert_num_gte("returned", 0)
        .assert_has("entries")
        .assert_array_min("entries", 0);
}

/// Test: get_missed_calls - Get missed calls
/// Category: call_history
#[tokio::test]
async fn test_get_missed_calls() {
    let client = McpTestClient::new().await;

    // Returns missed calls (empty in test environment)
    let result = client.call_tool("get_missed_calls", json!({})).await;

    result
        .assert_success()
        .assert_has("total")
        .assert_num_gte("total", 0)
        .assert_has("unread_count")
        .assert_num_gte("unread_count", 0)
        .assert_has("notifications")
        .assert_array_min("notifications", 0)
        .assert_has("last_updated");
}

// === CALL_RECORDING ===

/// Test: get_call_recording - Get recording
/// Category: call_recording
#[tokio::test]
async fn test_get_call_recording() {
    let client = McpTestClient::new().await;

    // Returns recording status (not recording in test environment)
    let result = client.call_tool("get_call_recording", json!({})).await;

    result
        .assert_success()
        .assert_has("is_recording")
        .assert_bool_eq("is_recording", false)
        .assert_has("state")
        .assert_has("is_paused")
        .assert_bool_eq("is_paused", false)
        .assert_has("is_in_call")
        .assert_bool_eq("is_in_call", false);
}

/// Test: start_call_recording - Start recording
/// Category: call_recording
#[tokio::test]
async fn test_start_call_recording() {
    let client = McpTestClient::new().await;

    // Requires an active call which doesn't exist in test environment
    let result = client.call_tool("start_call_recording", json!({})).await;

    result.assert_error();
}

/// Test: stop_call_recording - Stop recording
/// Category: call_recording
#[tokio::test]
async fn test_stop_call_recording() {
    let client = McpTestClient::new().await;

    // Requires an active recording which doesn't exist in test environment
    let result = client.call_tool("stop_call_recording", json!({})).await;

    result.assert_error();
}

// === CANVAS ===

/// Test: canvas_add_chart - Add chart element
/// Category: canvas
#[tokio::test]
async fn test_canvas_add_chart() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_add_chart", json!({})).await;

    result.assert_error();
}

/// Test: canvas_add_image - Add image element
/// Category: canvas
#[tokio::test]
async fn test_canvas_add_image() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_add_image", json!({})).await;

    result.assert_error();
}

/// Test: canvas_add_text - Add text element
/// Category: canvas
#[tokio::test]
async fn test_canvas_add_text() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_add_text", json!({})).await;

    result.assert_error();
}

/// Test: canvas_clear - Clear canvas
/// Category: canvas
#[tokio::test]
async fn test_canvas_clear() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_clear", json!({})).await;

    result.assert_error();
}

/// Test: canvas_deselect_all - Deselect all elements
/// Category: canvas
#[tokio::test]
async fn test_canvas_deselect_all() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_deselect_all", json!({})).await;

    result.assert_error();
}

/// Test: canvas_element_at - Get element at position
/// Category: canvas
#[tokio::test]
async fn test_canvas_element_at() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_element_at", json!({})).await;

    result.assert_error();
}

/// Test: canvas_remove_element - Remove element
/// Category: canvas
#[tokio::test]
async fn test_canvas_remove_element() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_remove_element", json!({})).await;

    result.assert_error();
}

/// Test: canvas_select_element - Select element
/// Category: canvas
#[tokio::test]
async fn test_canvas_select_element() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_select_element", json!({})).await;

    result.assert_error();
}

/// Test: canvas_update_transform - Update element transform
/// Category: canvas
#[tokio::test]
async fn test_canvas_update_transform() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_update_transform", json!({})).await;

    result.assert_error();
}

// === CANVAS_HISTORY ===

/// Test: canvas_export - Export canvas
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_export() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_export", json!({})).await;

    result.assert_error();
}

/// Test: canvas_get_history - Get canvas history
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_get_history() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_get_history", json!({})).await;

    result.assert_error();
}

/// Test: canvas_get_snapshot - Get canvas snapshot
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_get_snapshot() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_get_snapshot", json!({})).await;

    result.assert_error();
}

/// Test: canvas_import - Import canvas
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_import() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_import", json!({})).await;

    result.assert_error();
}

/// Test: canvas_redo - Redo undone action
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_redo() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_redo", json!({})).await;

    result.assert_error();
}

/// Test: canvas_undo - Undo last action
/// Category: canvas_history
#[tokio::test]
async fn test_canvas_undo() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_undo", json!({})).await;

    result.assert_error();
}

// === CANVAS_VIEW ===

/// Test: canvas_broadcast_cursor - Broadcast cursor position
/// Category: canvas_view
#[tokio::test]
async fn test_canvas_broadcast_cursor() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_broadcast_cursor", json!({})).await;

    result.assert_error();
}

/// Test: canvas_flush_offline_queue - Flush offline queue
/// Category: canvas_view
#[tokio::test]
async fn test_canvas_flush_offline_queue() {
    let client = McpTestClient::new().await;

    // Flush offline queue succeeds even without active canvas
    let result = client
        .call_tool(
            "canvas_flush_offline_queue",
            json!({
                "entity_id": "test-canvas-entity-123"
            }),
        )
        .await;

    result.assert_success();
}

/// Test: canvas_get_remote_cursors - Get remote cursors
/// Category: canvas_view
#[tokio::test]
async fn test_canvas_get_remote_cursors() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client
        .call_tool("canvas_get_remote_cursors", json!({}))
        .await;

    result.assert_error();
}

/// Test: canvas_set_view - Set view bounds
/// Category: canvas_view
#[tokio::test]
async fn test_canvas_set_view() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_set_view", json!({})).await;

    result.assert_error();
}

/// Test: canvas_set_viewport - Set viewport
/// Category: canvas_view
#[tokio::test]
async fn test_canvas_set_viewport() {
    let client = McpTestClient::new().await;

    // Requires a canvas context which doesn't exist in test environment
    let result = client.call_tool("canvas_set_viewport", json!({})).await;

    result.assert_error();
}

// === CONTACTS ===

/// Test: contacts - Query contacts (use list_contacts tool)
/// Category: contacts
#[tokio::test]
async fn test_contacts() {
    let client = McpTestClient::new().await;

    // Use the actual list_contacts tool
    // Note: In test environment without auth context, returns error (expected)
    let result = client.call_tool("list_contacts", json!({})).await;

    // Tool executes but may error without proper storage context
    // This validates the tool exists and responds
    result.assert_error();
}

/// Test: favorites - Query favorite contacts (use list_favourite_contacts tool)
/// Category: contacts
#[tokio::test]
async fn test_favorites() {
    let client = McpTestClient::new().await;

    // Use the actual list_favourite_contacts tool
    // Note: In test environment without auth context, returns error (expected)
    let result = client.call_tool("list_favourite_contacts", json!({})).await;

    // Tool executes but may error without proper storage context
    // This validates the tool exists and responds
    result.assert_error();
}

/// Test: get_contact_presence - Get contact presence status
/// Category: contacts
#[tokio::test]
async fn test_get_contact_presence() {
    let client = McpTestClient::new().await;

    // get_contact_presence requires an existing contact_id
    // Testing with non-existent ID should return error
    let result = client
        .call_tool(
            "get_contact_presence",
            json!({
                "contact_id": "non-existent-contact-id"
            }),
        )
        .await;

    // Non-existent contact returns error (expected behavior)
    result.assert_error();
}

// === DRIVE ===

/// Test: copy_file - Copy file
/// Category: drive
#[tokio::test]
async fn test_copy_file() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("copy_file", json!({})).await;

    result.assert_error();
}

/// Test: create_directory - Create directory
/// Category: drive
#[tokio::test]
async fn test_create_directory() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client
        .call_tool(
            "create_directory",
            json!({
                "name": "Test Item"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: get_file_preview - Get file preview
/// Category: drive
#[tokio::test]
async fn test_get_file_preview() {
    let client = McpTestClient::new().await;

    // Requires file which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_file_preview",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: list_disks - List virtual disks
/// Category: drive
#[tokio::test]
async fn test_list_disks() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client
        .call_tool(
            "list_disks",
            json!({
                "limit": 10
            }),
        )
        .await;

    result.assert_error();
}

/// Test: move_file - Move/rename file
/// Category: drive
#[tokio::test]
async fn test_move_file() {
    let client = McpTestClient::new().await;

    // Requires file which doesn't exist in test environment
    let result = client
        .call_tool(
            "move_file",
            json!({
                "id": "test-id-123", "target_id": "target-123"
            }),
        )
        .await;

    result.assert_error();
}

// === DRIVE_ACCESS ===

/// Test: private - Private disk access
/// Category: drive_access
#[tokio::test]
async fn test_private() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("private", json!({})).await;

    result.assert_error();
}

/// Test: public - Public disk access
/// Category: drive_access
#[tokio::test]
async fn test_public() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("public", json!({})).await;

    result.assert_error();
}

/// Test: shared - Shared disk access
/// Category: drive_access
#[tokio::test]
async fn test_shared() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("shared", json!({})).await;

    result.assert_error();
}

// === DRIVE_DOWNLOAD ===

/// Test: cancel_download - Cancel download
/// Category: drive_download
#[tokio::test]
async fn test_cancel_download() {
    let client = McpTestClient::new().await;

    // Requires active download which doesn't exist in test environment
    let result = client.call_tool("cancel_download", json!({})).await;

    result.assert_error();
}

/// Test: get_download_progress - Get download progress
/// Category: drive_download
#[tokio::test]
async fn test_get_download_progress() {
    let client = McpTestClient::new().await;

    // Requires active download which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_download_progress",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: resume_download - Resume interrupted download
/// Category: drive_download
#[tokio::test]
async fn test_resume_download() {
    let client = McpTestClient::new().await;

    // Requires paused download which doesn't exist in test environment
    let result = client.call_tool("resume_download", json!({})).await;

    result.assert_error();
}

/// Test: start_streaming_download - Start streaming download
/// Category: drive_download
#[tokio::test]
async fn test_start_streaming_download() {
    let client = McpTestClient::new().await;

    // Requires file which doesn't exist in test environment
    let result = client
        .call_tool("start_streaming_download", json!({}))
        .await;

    result.assert_error();
}

// === DRIVE_SHARING ===

/// Test: create_share_link - Create share link
/// Category: drive_sharing
#[tokio::test]
async fn test_create_share_link() {
    let client = McpTestClient::new().await;

    // Requires file which doesn't exist in test environment
    let result = client
        .call_tool(
            "create_share_link",
            json!({
                "name": "Test Item"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: get_file_share_links - Get file share links
/// Category: drive_sharing
#[tokio::test]
async fn test_get_file_share_links() {
    let client = McpTestClient::new().await;

    // Requires file which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_file_share_links",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: list_share_links - List share links
/// Category: drive_sharing
#[tokio::test]
async fn test_list_share_links() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client
        .call_tool(
            "list_share_links",
            json!({
                "limit": 10
            }),
        )
        .await;

    result.assert_error();
}

/// Test: revoke_share_link - Revoke share link
/// Category: drive_sharing
#[tokio::test]
async fn test_revoke_share_link() {
    let client = McpTestClient::new().await;

    // Requires share link which doesn't exist in test environment
    let result = client.call_tool("revoke_share_link", json!({})).await;

    result.assert_error();
}

// === DRIVE_STAGING ===

/// Test: get_staged_upload - Get staged upload
/// Category: drive_staging
#[tokio::test]
async fn test_get_staged_upload() {
    let client = McpTestClient::new().await;

    // Requires staged upload which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_staged_upload",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: get_staging_status - Get staging status
/// Category: drive_staging
#[tokio::test]
async fn test_get_staging_status() {
    let client = McpTestClient::new().await;

    // Requires staging context which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_staging_status",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: keep_both - Keep both versions
/// Category: drive_staging
#[tokio::test]
async fn test_keep_both() {
    let client = McpTestClient::new().await;

    // Requires conflict which doesn't exist in test environment
    let result = client.call_tool("keep_both", json!({})).await;

    result.assert_error();
}

/// Test: keep_local - Keep local version
/// Category: drive_staging
#[tokio::test]
async fn test_keep_local() {
    let client = McpTestClient::new().await;

    // Requires conflict which doesn't exist in test environment
    let result = client.call_tool("keep_local", json!({})).await;

    result.assert_error();
}

/// Test: keep_remote - Keep remote version
/// Category: drive_staging
#[tokio::test]
async fn test_keep_remote() {
    let client = McpTestClient::new().await;

    // Requires conflict which doesn't exist in test environment
    let result = client.call_tool("keep_remote", json!({})).await;

    result.assert_error();
}

/// Test: list_staged_uploads - List staged uploads
/// Category: drive_staging
#[tokio::test]
async fn test_list_staged_uploads() {
    let client = McpTestClient::new().await;

    // Requires staging context which doesn't exist in test environment
    let result = client
        .call_tool(
            "list_staged_uploads",
            json!({
                "limit": 10
            }),
        )
        .await;

    result.assert_error();
}

/// Test: remove_staged_upload - Remove staged upload
/// Category: drive_staging
#[tokio::test]
async fn test_remove_staged_upload() {
    let client = McpTestClient::new().await;

    // Requires staged upload which doesn't exist in test environment
    let result = client
        .call_tool(
            "remove_staged_upload",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: resolve_staging_conflict - Resolve staging conflict
/// Category: drive_staging
#[tokio::test]
async fn test_resolve_staging_conflict() {
    let client = McpTestClient::new().await;

    // Requires conflict which doesn't exist in test environment
    let result = client
        .call_tool("resolve_staging_conflict", json!({}))
        .await;

    result.assert_error();
}

/// Test: retry_staged_upload - Retry staged upload
/// Category: drive_staging
#[tokio::test]
async fn test_retry_staged_upload() {
    let client = McpTestClient::new().await;

    // Requires failed upload which doesn't exist in test environment
    let result = client.call_tool("retry_staged_upload", json!({})).await;

    result.assert_error();
}

/// Test: stage_upload - Stage file for upload
/// Category: drive_staging
#[tokio::test]
async fn test_stage_upload() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("stage_upload", json!({})).await;

    result.assert_error();
}

/// Test: sync_staging_queue - Sync staging queue
/// Category: drive_staging
#[tokio::test]
async fn test_sync_staging_queue() {
    let client = McpTestClient::new().await;

    // Requires staging context which doesn't exist in test environment
    let result = client.call_tool("sync_staging_queue", json!({})).await;

    result.assert_error();
}

// === DRIVE_UPLOAD ===

/// Test: cancel_upload - Cancel upload
/// Category: drive_upload
#[tokio::test]
async fn test_cancel_upload() {
    let client = McpTestClient::new().await;

    // Requires active upload which doesn't exist in test environment
    let result = client.call_tool("cancel_upload", json!({})).await;

    result.assert_error();
}

/// Test: get_upload_progress - Get upload progress
/// Category: drive_upload
#[tokio::test]
async fn test_get_upload_progress() {
    let client = McpTestClient::new().await;

    // Requires active upload which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_upload_progress",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: resume_upload - Resume interrupted upload
/// Category: drive_upload
#[tokio::test]
async fn test_resume_upload() {
    let client = McpTestClient::new().await;

    // Requires paused upload which doesn't exist in test environment
    let result = client.call_tool("resume_upload", json!({})).await;

    result.assert_error();
}

/// Test: start_streaming_upload - Start streaming upload
/// Category: drive_upload
#[tokio::test]
async fn test_start_streaming_upload() {
    let client = McpTestClient::new().await;

    // Requires drive context which doesn't exist in test environment
    let result = client.call_tool("start_streaming_upload", json!({})).await;

    result.assert_error();
}

// === ENTITIES ===

/// Test: channel - Entity type shorthand (use create_entity with entity_type="channel")
/// Category: entities
#[tokio::test]
async fn test_channel() {
    let client = McpTestClient::new().await;

    // Use the actual create_entity tool with channel type
    let result = client
        .call_tool(
            "create_entity",
            json!({
                "name": "Test Channel",
                "entity_type": "channel"
            }),
        )
        .await;

    // create_entity returns: {success, events, message, id}
    result
        .assert_success()
        .assert_has("id")
        .assert_bool_eq("success", true)
        .assert_has("message")
        .assert_num_gte("events", 1);
}

/// Test: entities - Query entities (use list_entities tool)
/// Category: entities
#[tokio::test]
async fn test_entities() {
    let client = McpTestClient::new().await;

    // Use the actual list_entities tool
    let result = client.call_tool("list_entities", json!({})).await;

    result
        .assert_success()
        .assert_has("entities")
        .assert_array_min("entities", 0);
}

/// Test: group - Entity type shorthand (use create_entity with entity_type="group")
/// Category: entities
#[tokio::test]
async fn test_group() {
    let client = McpTestClient::new().await;

    // Use the actual create_entity tool with group type
    let result = client
        .call_tool(
            "create_entity",
            json!({
                "name": "Test Group",
                "entity_type": "group"
            }),
        )
        .await;

    // create_entity returns: {success, events, message, id}
    result
        .assert_success()
        .assert_has("id")
        .assert_bool_eq("success", true)
        .assert_has("message")
        .assert_num_gte("events", 1);
}

/// Test: person - Test get_entity for entity lookup (person contacts use contacts tools)
/// Category: entities
#[tokio::test]
async fn test_person() {
    let client = McpTestClient::new().await;

    // Note: "person" as an entity type is handled through the contacts system, not entities
    // This test verifies get_entity works for looking up entities by ID
    // Using a non-existent ID to verify error handling
    let result = client
        .call_tool(
            "get_entity",
            json!({
                "entity_id": "non-existent-entity-id"
            }),
        )
        .await;

    // get_entity returns an error for non-existent entities, which is expected behavior
    result.assert_error();
}

/// Test: project - Entity type shorthand (use create_entity with entity_type="project")
/// Category: entities
#[tokio::test]
async fn test_project() {
    let client = McpTestClient::new().await;

    // Use the actual create_entity tool with project type
    let result = client
        .call_tool(
            "create_entity",
            json!({
                "name": "Test Project",
                "entity_type": "project"
            }),
        )
        .await;

    // create_entity returns: {success, events, message, id}
    result
        .assert_success()
        .assert_has("id")
        .assert_bool_eq("success", true)
        .assert_has("message")
        .assert_num_gte("events", 1);
}

// === IDENTITY ===

/// Test: create_identity - Create a new identity with mnemonic
/// Category: identity
#[tokio::test]
async fn test_create_identity() {
    let client = McpTestClient::new().await;

    // Create identity with 12-word mnemonic for faster tests
    let result = client
        .call_tool(
            "create_identity",
            json!({
                "word_count": 12
            }),
        )
        .await;

    result
        .assert_success()
        .assert_has("mnemonic_words")
        .assert_array_min("mnemonic_words", 12)
        .assert_has("four_words")
        .assert_non_empty("four_words")
        .assert_has("public_signing_key")
        .assert_non_empty("public_signing_key")
        .assert_has("public_encryption_key")
        .assert_non_empty("public_encryption_key")
        .assert_has("warning");
}

/// Test: export_audit_log - Export audit log
/// Category: identity
#[tokio::test]
async fn test_export_audit_log() {
    let client = McpTestClient::new().await;

    // Export requires start_date and end_date
    let result = client
        .call_tool(
            "export_audit_log",
            json!({
                "start_date": "2026-01-01T00:00:00Z",
                "end_date": "2026-12-31T23:59:59Z"
            }),
        )
        .await;

    result
        .assert_success()
        .assert_has("events")
        .assert_array_min("events", 0)
        .assert_has("count")
        .assert_num_gte("count", 0)
        .assert_has("start_date")
        .assert_has("end_date");
}

/// Test: get_audit_log - Get audit log entries
/// Category: identity
#[tokio::test]
async fn test_get_audit_log() {
    let client = McpTestClient::new().await;

    // Get recent audit events with default limit
    let result = client
        .call_tool(
            "get_audit_log",
            json!({
                "limit": 10
            }),
        )
        .await;

    result
        .assert_success()
        .assert_has("events")
        .assert_array_min("events", 0)
        .assert_has("count")
        .assert_num_gte("count", 0)
        .assert_has("limit")
        .assert_num_gte("limit", 1);
}

/// Test: recover_identity - Recover identity from mnemonic
/// Category: identity
#[tokio::test]
async fn test_recover_identity() {
    let client = McpTestClient::new().await;

    // Test with valid 12-word mnemonic
    let result = client
        .call_tool(
            "recover_identity",
            json!({
                "mnemonic_words": "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
            }),
        )
        .await;

    result.assert_success();
}

/// Test: validate_mnemonic - Validate mnemonic words
/// Category: identity
#[tokio::test]
async fn test_validate_mnemonic() {
    let client = McpTestClient::new().await;

    // Test with valid 12-word mnemonic
    let result = client
        .call_tool(
            "validate_mnemonic",
            json!({
                "mnemonic_words": "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
            }),
        )
        .await;

    result.assert_success();
}

// === MESSAGING ===

/// Test: get_pinned_threads - Get pinned threads
/// Category: messaging
#[tokio::test]
async fn test_get_pinned_threads() {
    let client = McpTestClient::new().await;

    // Tool works without parameters
    let result = client.call_tool("get_pinned_threads", json!({})).await;

    // Returns pinned_threads list (may be empty)
    result.assert_success().assert_has("pinned_threads");
}

/// Test: get_typing_users - Get typing users in a thread
/// Category: messaging
#[tokio::test]
async fn test_get_typing_users() {
    let client = McpTestClient::new().await;

    // Works with any thread_id, returns empty typing_users if none
    let result = client
        .call_tool(
            "get_typing_users",
            json!({
                "thread_id": "test-thread"
            }),
        )
        .await;

    result
        .assert_success()
        .assert_has("thread_id")
        .assert_has("typing_users")
        .assert_array_min("typing_users", 0);
}

/// Test: list_messages - List messages
/// Category: messaging
#[tokio::test]
async fn test_list_messages() {
    let client = McpTestClient::new().await;

    // Requires entity_id and entity_type - errors without them
    let result = client
        .call_tool(
            "list_messages",
            json!({
                "entity_id": "non-existent-entity",
                "entity_type": "channel"
            }),
        )
        .await;

    // Tool executes but errors for invalid entity (expected)
    result.assert_error();
}

/// Test: list_threads - List threads
/// Category: messaging
#[tokio::test]
async fn test_list_threads() {
    let client = McpTestClient::new().await;

    // list_threads requires MessagingService context
    let result = client.call_tool("list_threads", json!({})).await;

    // Tool executes but may error without proper storage context
    result.assert_error();
}

/// Test: mark_thread_read - Mark thread as read
/// Category: messaging
#[tokio::test]
async fn test_mark_thread_read() {
    let client = McpTestClient::new().await;

    // Requires thread_id - errors without valid thread
    let result = client
        .call_tool(
            "mark_thread_read",
            json!({
                "thread_id": "non-existent-thread"
            }),
        )
        .await;

    // Tool executes but errors for invalid thread (expected)
    result.assert_error();
}

/// Test: pin_thread - Pin a thread
/// Category: messaging
#[tokio::test]
async fn test_pin_thread() {
    let client = McpTestClient::new().await;

    // Requires thread_id - errors without valid thread
    let result = client
        .call_tool(
            "pin_thread",
            json!({
                "thread_id": "non-existent-thread"
            }),
        )
        .await;

    // Tool executes but errors for invalid thread (expected)
    result.assert_error();
}

/// Test: search_messages - Search messages
/// Category: messaging
#[tokio::test]
async fn test_search_messages() {
    let client = McpTestClient::new().await;

    // Search requires MessagingService context
    let result = client
        .call_tool(
            "search_messages",
            json!({
                "query": "test"
            }),
        )
        .await;

    // Tool executes but may error without proper storage context
    result.assert_error();
}

/// Test: send_typing_indicator - Send typing indicator
/// Category: messaging
#[tokio::test]
async fn test_send_typing_indicator() {
    let client = McpTestClient::new().await;

    // Requires thread_id - errors without valid context
    let result = client
        .call_tool(
            "send_typing_indicator",
            json!({
                "thread_id": "non-existent-thread"
            }),
        )
        .await;

    // Tool executes but errors for invalid thread (expected)
    result.assert_error();
}

/// Test: unpin_thread - Unpin a thread
/// Category: messaging
#[tokio::test]
async fn test_unpin_thread() {
    let client = McpTestClient::new().await;

    // Requires thread_id - errors without valid thread
    let result = client
        .call_tool(
            "unpin_thread",
            json!({
                "thread_id": "non-existent-thread"
            }),
        )
        .await;

    // Tool executes but errors for invalid thread (expected)
    result.assert_error();
}

/// Test: unread - Mark as unread (uses unread tool)
/// Category: messaging
#[tokio::test]
async fn test_unread() {
    let client = McpTestClient::new().await;

    // "unread" isn't a standalone tool - it's an action requiring thread_id
    // Testing that unknown tool returns error
    let result = client.call_tool("unread", json!({})).await;

    // Tool doesn't exist as standalone - returns error
    result.assert_error();
}

// === NETWORK ===

/// Test: connect_by_words - Connect by four words
/// Category: network
#[tokio::test]
async fn test_connect_by_words() {
    let client = McpTestClient::new().await;

    // Requires valid four-words which doesn't exist in test environment
    let result = client.call_tool("connect_by_words", json!({})).await;

    result.assert_error();
}

/// Test: get_connection_words - Get connection words
/// Category: network
#[tokio::test]
async fn test_get_connection_words() {
    let client = McpTestClient::new().await;

    // Returns connection words for the local node (may be None if no external address)
    let result = client.call_tool("get_connection_words", json!({})).await;

    // Either returns connection_words or an error message
    result.assert_success();
}

/// Test: set_network_available - Set network availability
/// Category: network
#[tokio::test]
async fn test_set_network_available() {
    let client = McpTestClient::new().await;

    // Requires network context which doesn't exist in test environment
    let result = client.call_tool("set_network_available", json!({})).await;

    result.assert_error();
}

// === OFFLINE_QUEUE ===

/// Test: cancel_pending_message - Cancel pending message
/// Category: offline_queue
#[tokio::test]
async fn test_cancel_pending_message() {
    let client = McpTestClient::new().await;

    // Requires pending message which doesn't exist in test environment
    let result = client.call_tool("cancel_pending_message", json!({})).await;

    result.assert_error();
}

/// Test: get_pending_messages - Get pending messages
/// Category: offline_queue
#[tokio::test]
async fn test_get_pending_messages() {
    let client = McpTestClient::new().await;

    // Returns pending messages (empty in test environment)
    let result = client.call_tool("get_pending_messages", json!({})).await;

    result
        .assert_success()
        .assert_has("pending_messages")
        .assert_array_min("pending_messages", 0);
}

/// Test: queue_offline_message - Queue message for offline
/// Category: offline_queue
#[tokio::test]
async fn test_queue_offline_message() {
    let client = McpTestClient::new().await;

    // Requires message context which doesn't exist in test environment
    let result = client.call_tool("queue_offline_message", json!({})).await;

    result.assert_error();
}

/// Test: retry - Retry operation
/// Category: offline_queue
#[tokio::test]
async fn test_retry() {
    let client = McpTestClient::new().await;

    // Requires failed operation which doesn't exist in test environment
    let result = client.call_tool("retry", json!({})).await;

    result.assert_error();
}

/// Test: retry_pending_messages - Retry pending messages
/// Category: offline_queue
#[tokio::test]
async fn test_retry_pending_messages() {
    let client = McpTestClient::new().await;

    // Retries all pending messages (succeeds even with empty queue)
    let result = client.call_tool("retry_pending_messages", json!({})).await;

    result.assert_success();
}

/// Test: skip - Skip operation
/// Category: offline_queue
#[tokio::test]
async fn test_skip() {
    let client = McpTestClient::new().await;

    // Requires skippable operation which doesn't exist in test environment
    let result = client.call_tool("skip", json!({})).await;

    result.assert_error();
}

// === PRESENCE ===

/// Test: announce_presence - Announce presence
/// Category: presence
#[tokio::test]
async fn test_announce_presence() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("announce_presence", json!({})).await;

    result.assert_error();
}

/// Test: away - Set away status
/// Category: presence
#[tokio::test]
async fn test_away() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("away", json!({})).await;

    result.assert_error();
}

/// Test: busy - Set busy status
/// Category: presence
#[tokio::test]
async fn test_busy() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("busy", json!({})).await;

    result.assert_error();
}

/// Test: get_cached_presence - Get cached presence
/// Category: presence
#[tokio::test]
async fn test_get_cached_presence() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client
        .call_tool(
            "get_cached_presence",
            json!({
                "id": "test-id-123"
            }),
        )
        .await;

    result.assert_error();
}

/// Test: get_our_presence - Get own presence
/// Category: presence
#[tokio::test]
async fn test_get_our_presence() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("get_our_presence", json!({})).await;

    result.assert_error();
}

/// Test: invisible - Set invisible status
/// Category: presence
#[tokio::test]
async fn test_invisible() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("invisible", json!({})).await;

    result.assert_error();
}

/// Test: offline - Set offline status
/// Category: presence
#[tokio::test]
async fn test_offline() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("offline", json!({})).await;

    result.assert_error();
}

/// Test: online - Set online status
/// Category: presence
#[tokio::test]
async fn test_online() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("online", json!({})).await;

    result.assert_error();
}

/// Test: query_presence - Query presence
/// Category: presence
#[tokio::test]
async fn test_query_presence() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("query_presence", json!({})).await;

    result.assert_error();
}

/// Test: set_my_presence - Set own presence
/// Category: presence
#[tokio::test]
async fn test_set_my_presence() {
    let client = McpTestClient::new().await;

    // Requires identity context which doesn't exist in test environment
    let result = client.call_tool("set_my_presence", json!({})).await;

    result.assert_error();
}
