// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'flutter_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `execute_command_raw`, `execute_command`, `execute_query`, `map_event`, `split_four_words`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize the Rust tracing system for Flutter debugging.
///
/// This function sets up a tracing subscriber that outputs logs to stdout,
/// which Flutter can capture and display in the debug console.
///
/// # Arguments
/// * `level` - Optional log level filter (e.g., "info", "debug", "warn").
///             If not provided, defaults to "info" or respects RUST_LOG env var.
///
/// # Returns
/// * `Ok(true)` - Tracing was successfully initialized
/// * `Ok(false)` - Tracing was already initialized (no-op)
/// * `Err(String)` - Failed to initialize tracing
///
/// # Example
/// Call this from Flutter before any other Rust operations:
/// ```dart
/// await initializeTracing(level: "debug");
/// ```
Future<bool> initializeTracing({String? level}) => RustLib.instance.api.crateFlutterApiInitializeTracing(level: level);

/// Generate a random four-word identity
Future<String> generateIdWords() => RustLib.instance.api.crateFlutterApiGenerateIdWords();

Future<bool> validateRecoveryMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateFlutterApiValidateRecoveryMnemonic(mnemonic: mnemonic);

Future<FlutterRecoveredIdentity> previewIdentityFromMnemonic({required String mnemonic, String? passphrase}) =>
    RustLib.instance.api.crateFlutterApiPreviewIdentityFromMnemonic(mnemonic: mnemonic, passphrase: passphrase);

Future<FlutterRecoveredIdentity> recoverIdentityFromMnemonic({required String mnemonic, String? passphrase}) =>
    RustLib.instance.api.crateFlutterApiRecoverIdentityFromMnemonic(mnemonic: mnemonic, passphrase: passphrase);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CommunitasApi>>
abstract class CommunitasApi implements RustOpaqueInterface {
  Future<String> authCreateVault({required String fourWords, required String displayName, required String password});

  Future<void> authDeleteVault({required String fourWords, required String password});

  Future<String> authExportVault({required bool includeData});

  Future<FlutterSessionInfo?> authGetCurrentSession();

  Future<String> authImportVault({required String backupBase64, required String password});

  Future<List<FlutterVaultInfo>> authListVaults();

  Future<FlutterSessionInfo> authLogin({required String fourWords, required String password});

  Future<void> authLogout();

  Future<bool> authVaultExists({required String fourWords});

  Future<List<FlutterEvent>> contactCreate({required String displayName, String? fourWords, required bool isFavourite});

  Future<List<FlutterEvent>> contactDelete({required String contactId});

  Future<FlutterContact> contactGet({required String contactId});

  Future<List<FlutterEvent>> contactLink({required String contactId, required String fourWords});

  Future<List<FlutterEvent>> contactRemoveFavourite({required String fourWords});

  Future<List<FlutterEvent>> contactSetFavourite({required String fourWords});

  Future<List<FlutterEvent>> contactUpdate({required String contactId, String? displayName, bool? isFavourite});

  Future<List<FlutterContact>> contactsList();

  Future<List<FlutterContact>> contactsListFavourites();

  Future<List<FlutterContact>> contactsSearch({required String query});

  /// Initialize the API with the given identity and storage path
  static Future<CommunitasApi> create(
          {required String fourWords,
          required String displayName,
          required String deviceName,
          required String storagePath}) =>
      RustLib.instance.api.crateFlutterApiCommunitasApiCreate(
          fourWords: fourWords, displayName: displayName, deviceName: deviceName, storagePath: storagePath);

  Future<List<FlutterEvent>> diskCreateDirectory(
      {required String entityId, required FlutterDiskType diskType, required String path});

  Future<List<FlutterEvent>> diskDeleteFile(
      {required String entityId, required FlutterDiskType diskType, required String path});

  Future<FlutterDiskStats> diskGetStats({required String entityId, required FlutterDiskType diskType});

  Future<List<FlutterFileInfo>> diskListFiles(
      {required String entityId, required FlutterDiskType diskType, required String path});

  Future<Uint8List> diskReadFile({required String entityId, required FlutterDiskType diskType, required String path});

  Future<List<FlutterEvent>> diskWriteFile(
      {required String entityId, required FlutterDiskType diskType, required String path, required List<int> data});

  Future<List<FlutterEvent>> entityAddMember(
      {required FlutterEntityType entityType,
      required String entityId,
      required String memberId,
      required String role});

  Future<List<FlutterEvent>> entityCreate(
      {required String name, required FlutterEntityType entityType, String? description, String? parentOrgId});

  Future<FlutterEntity> entityGet({required String entityId});

  Future<List<FlutterEntity>> entityList();

  Future<List<FlutterEntity>> entityListByType({required FlutterEntityType entityType});

  Future<List<FlutterEvent>> entityRemoveMember(
      {required FlutterEntityType entityType, required String entityId, required String memberId});

  Future<FlutterUserProfile> getProfile();

  Future<List<FlutterEvent>> gossipConnectToPeer({required String fourWords});

  Future<String?> gossipGetConnectionWords();

  Future<FlutterNetworkInfo> gossipGetNetworkInfo();

  Future<List<FlutterEvent>> gossipStart({int? port});

  Future<List<FlutterEvent>> gossipStop();

  Future<List<FlutterEvent>> inviteAccept({required String inviteId});

  Future<List<FlutterEvent>> inviteCreate(
      {required String recipientId,
      required FlutterEntityType entityType,
      required String entityId,
      required String role,
      String? message});

  Future<List<FlutterEvent>> inviteReject({required String inviteId});

  Future<List<FlutterEvent>> inviteRevoke({required String inviteId});

  Future<FlutterKanbanBoard> kanbanCreateBoard(
      {required String entityId, required String boardName, String? description});

  Future<FlutterKanbanCard> kanbanCreateCard(
      {required String boardId,
      required String columnId,
      required String title,
      String? description,
      String? assignee});

  Future<FlutterKanbanColumn> kanbanCreateColumn({required String boardId, required String columnName, int? position});

  Future<List<FlutterEvent>> kanbanDeleteCard({required String boardId, required String cardId});

  Future<FlutterKanbanBoard> kanbanGetBoard({required String boardId});

  Future<List<FlutterKanbanBoard>> kanbanListBoards({required String entityId});

  Future<List<FlutterKanbanCard>> kanbanListCards(
      {required String boardId, String? columnId, String? state, String? assigneeId, String? tagId});

  Future<List<FlutterKanbanColumn>> kanbanListColumns({required String boardId});

  Future<List<FlutterEvent>> kanbanMoveCard(
      {required String boardId, required String cardId, required String targetColumnId, int? position});

  Future<List<FlutterEvent>> kanbanUpdateCard(
      {required String boardId, required String cardId, String? title, String? description, String? assignee});

  Future<List<FlutterEvent>> messageAddReaction(
      {required String entityId,
      required FlutterEntityType entityType,
      required String messageId,
      required String emoji});

  Future<List<FlutterEvent>> messageDelete(
      {required String entityId, required FlutterEntityType entityType, required String messageId});

  Future<List<FlutterEvent>> messageEdit(
      {required String entityId,
      required FlutterEntityType entityType,
      required String messageId,
      required String newText});

  Future<FlutterMessage> messageGet({required String entityId, required String messageId});

  Future<List<FlutterMessage>> messageList({required String entityId});

  Future<List<FlutterMessage>> messageListDirect({required String otherPeerId});

  Future<List<FlutterMessage>> messageListThread({required String entityId, required String parentMessageId});

  Future<List<FlutterEvent>> messageRemoveReaction(
      {required String entityId,
      required FlutterEntityType entityType,
      required String messageId,
      required String emoji});

  Future<List<FlutterEvent>> messageSend(
      {required String entityId, required FlutterEntityType entityType, required String text, String? replyToId});

  Future<List<FlutterEvent>> messageSendDirect({required List<String> recipients, required String text});

  Future<List<FlutterEvent>> presenceAnnounce();

  Future<FlutterPresenceRecord?> presenceGetCachedPeer({required String pubkeyHex});

  Future<FlutterPresenceRecord?> presenceGetOurRecord();

  Future<FlutterPresenceStatus> presenceGetStatus({required String peerId});

  Future<List<String>> presenceListOnlinePeers();

  Future<FlutterPresenceRecord?> presenceQueryPeer({required String pubkeyHex});

  Future<List<FlutterEvent>> updateDisplayName({required String displayName});
}

/// Contact response data
class FlutterContact {
  final String id;
  final String displayName;
  final String? fourWords;
  final bool isFavourite;
  final bool isOnline;
  final PlatformInt64 createdAt;
  final PlatformInt64? lastSeen;

  const FlutterContact({
    required this.id,
    required this.displayName,
    this.fourWords,
    required this.isFavourite,
    required this.isOnline,
    required this.createdAt,
    this.lastSeen,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      fourWords.hashCode ^
      isFavourite.hashCode ^
      isOnline.hashCode ^
      createdAt.hashCode ^
      lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterContact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          fourWords == other.fourWords &&
          isFavourite == other.isFavourite &&
          isOnline == other.isOnline &&
          createdAt == other.createdAt &&
          lastSeen == other.lastSeen;
}

/// Disk stats response data
class FlutterDiskStats {
  final String entityId;
  final FlutterDiskType diskType;
  final BigInt usedBytes;
  final int fileCount;
  final int dirCount;

  const FlutterDiskStats({
    required this.entityId,
    required this.diskType,
    required this.usedBytes,
    required this.fileCount,
    required this.dirCount,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^ diskType.hashCode ^ usedBytes.hashCode ^ fileCount.hashCode ^ dirCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDiskStats &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          diskType == other.diskType &&
          usedBytes == other.usedBytes &&
          fileCount == other.fileCount &&
          dirCount == other.dirCount;
}

/// Disk type enumeration
enum FlutterDiskType {
  private,
  public,
  shared,
  ;
}

/// Entity information
class FlutterEntity {
  final String id;
  final String name;
  final FlutterEntityType entityType;
  final String? description;
  final String createdBy;
  final PlatformInt64 createdAt;
  final BigInt memberCount;
  final String? parentOrgId;
  final String? networkFourWords;
  final bool isLocalOnly;

  const FlutterEntity({
    required this.id,
    required this.name,
    required this.entityType,
    this.description,
    required this.createdBy,
    required this.createdAt,
    required this.memberCount,
    this.parentOrgId,
    this.networkFourWords,
    required this.isLocalOnly,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      entityType.hashCode ^
      description.hashCode ^
      createdBy.hashCode ^
      createdAt.hashCode ^
      memberCount.hashCode ^
      parentOrgId.hashCode ^
      networkFourWords.hashCode ^
      isLocalOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          entityType == other.entityType &&
          description == other.description &&
          createdBy == other.createdBy &&
          createdAt == other.createdAt &&
          memberCount == other.memberCount &&
          parentOrgId == other.parentOrgId &&
          networkFourWords == other.networkFourWords &&
          isLocalOnly == other.isLocalOnly;
}

/// Entity type enumeration
enum FlutterEntityType {
  group,
  channel,
  project,
  organisation,
  person,
  ;
}

@freezed
sealed class FlutterEvent with _$FlutterEvent {
  const FlutterEvent._();

  const factory FlutterEvent.networkingStarted({
    required String address,
  }) = FlutterEvent_NetworkingStarted;
  const factory FlutterEvent.networkingStopped() = FlutterEvent_NetworkingStopped;
  const factory FlutterEvent.peerConnected({
    required String peerId,
  }) = FlutterEvent_PeerConnected;
  const factory FlutterEvent.peerDisconnected({
    required String peerId,
  }) = FlutterEvent_PeerDisconnected;
  const factory FlutterEvent.entityCreated({
    required String entityId,
  }) = FlutterEvent_EntityCreated;
  const factory FlutterEvent.entityUpdated({
    required String entityId,
  }) = FlutterEvent_EntityUpdated;
  const factory FlutterEvent.messageSent({
    required String messageId,
    required String entityId,
  }) = FlutterEvent_MessageSent;
  const factory FlutterEvent.messageReceived({
    required String messageId,
    required String entityId,
  }) = FlutterEvent_MessageReceived;
  const factory FlutterEvent.directMessageSent({
    required List<String> messageIds,
    required List<String> recipients,
  }) = FlutterEvent_DirectMessageSent;
  const factory FlutterEvent.messageDeleted({
    required String messageId,
    required String entityId,
  }) = FlutterEvent_MessageDeleted;
  const factory FlutterEvent.messageEdited({
    required String messageId,
    required String entityId,
    required String newText,
    required BigInt editedAt,
  }) = FlutterEvent_MessageEdited;
  const factory FlutterEvent.reactionAdded({
    required String messageId,
    required String entityId,
    required String emoji,
    required String reactorId,
  }) = FlutterEvent_ReactionAdded;
  const factory FlutterEvent.reactionRemoved({
    required String messageId,
    required String entityId,
    required String emoji,
    required String reactorId,
  }) = FlutterEvent_ReactionRemoved;
  const factory FlutterEvent.inviteCreated({
    required String inviteId,
  }) = FlutterEvent_InviteCreated;
  const factory FlutterEvent.inviteAccepted({
    required String inviteId,
  }) = FlutterEvent_InviteAccepted;
  const factory FlutterEvent.inviteRejected({
    required String inviteId,
  }) = FlutterEvent_InviteRejected;
  const factory FlutterEvent.inviteRevoked({
    required String inviteId,
  }) = FlutterEvent_InviteRevoked;
  const factory FlutterEvent.fileWritten({
    required String entityId,
    required String path,
  }) = FlutterEvent_FileWritten;
  const factory FlutterEvent.fileDeleted({
    required String entityId,
    required String path,
  }) = FlutterEvent_FileDeleted;
  const factory FlutterEvent.error({
    required String code,
    required String message,
  }) = FlutterEvent_Error;
}

/// File info response data
class FlutterFileInfo {
  final String path;
  final String name;
  final bool isDirectory;
  final BigInt sizeBytes;
  final PlatformInt64 modifiedAt;

  const FlutterFileInfo({
    required this.path,
    required this.name,
    required this.isDirectory,
    required this.sizeBytes,
    required this.modifiedAt,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ isDirectory.hashCode ^ sizeBytes.hashCode ^ modifiedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterFileInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDirectory == other.isDirectory &&
          sizeBytes == other.sizeBytes &&
          modifiedAt == other.modifiedAt;
}

/// Kanban board response data
class FlutterKanbanBoard {
  final String id;
  final String entityId;
  final String name;
  final String? description;
  final int columnCount;

  const FlutterKanbanBoard({
    required this.id,
    required this.entityId,
    required this.name,
    this.description,
    required this.columnCount,
  });

  @override
  int get hashCode => id.hashCode ^ entityId.hashCode ^ name.hashCode ^ description.hashCode ^ columnCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterKanbanBoard &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityId == other.entityId &&
          name == other.name &&
          description == other.description &&
          columnCount == other.columnCount;
}

/// Kanban card response data
class FlutterKanbanCard {
  final String id;
  final String columnId;
  final String title;
  final String? description;
  final String? assignee;
  final int position;

  const FlutterKanbanCard({
    required this.id,
    required this.columnId,
    required this.title,
    this.description,
    this.assignee,
    required this.position,
  });

  @override
  int get hashCode =>
      id.hashCode ^ columnId.hashCode ^ title.hashCode ^ description.hashCode ^ assignee.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterKanbanCard &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          columnId == other.columnId &&
          title == other.title &&
          description == other.description &&
          assignee == other.assignee &&
          position == other.position;
}

/// Kanban column response data
class FlutterKanbanColumn {
  final String id;
  final String boardId;
  final String name;
  final int position;
  final String? color;
  final int? wipLimit;

  const FlutterKanbanColumn({
    required this.id,
    required this.boardId,
    required this.name,
    required this.position,
    this.color,
    this.wipLimit,
  });

  @override
  int get hashCode =>
      id.hashCode ^ boardId.hashCode ^ name.hashCode ^ position.hashCode ^ color.hashCode ^ wipLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterKanbanColumn &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          boardId == other.boardId &&
          name == other.name &&
          position == other.position &&
          color == other.color &&
          wipLimit == other.wipLimit;
}

/// Message response data
class FlutterMessage {
  final String id;
  final String entityId;
  final String author;
  final String text;
  final PlatformInt64 timestamp;
  final String? replyToId;
  final List<FlutterReaction> reactions;
  final BigInt? editedAt;

  const FlutterMessage({
    required this.id,
    required this.entityId,
    required this.author,
    required this.text,
    required this.timestamp,
    this.replyToId,
    required this.reactions,
    this.editedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityId.hashCode ^
      author.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      replyToId.hashCode ^
      reactions.hashCode ^
      editedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityId == other.entityId &&
          author == other.author &&
          text == other.text &&
          timestamp == other.timestamp &&
          replyToId == other.replyToId &&
          reactions == other.reactions &&
          editedAt == other.editedAt;
}

/// Network status information
class FlutterNetworkInfo {
  final bool isActive;
  final int? boundPort;
  final int peerCount;
  final String? externalAddress;
  final bool bootstrapConnected;

  /// Number of bootstrap nodes in the peer cache
  final int bootstrapCount;

  const FlutterNetworkInfo({
    required this.isActive,
    this.boundPort,
    required this.peerCount,
    this.externalAddress,
    required this.bootstrapConnected,
    required this.bootstrapCount,
  });

  @override
  int get hashCode =>
      isActive.hashCode ^
      boundPort.hashCode ^
      peerCount.hashCode ^
      externalAddress.hashCode ^
      bootstrapConnected.hashCode ^
      bootstrapCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterNetworkInfo &&
          runtimeType == other.runtimeType &&
          isActive == other.isActive &&
          boundPort == other.boundPort &&
          peerCount == other.peerCount &&
          externalAddress == other.externalAddress &&
          bootstrapConnected == other.bootstrapConnected &&
          bootstrapCount == other.bootstrapCount;
}

/// Presence record exposed to Flutter
class FlutterPresenceRecord {
  final String pubkeyHex;
  final String connectionWords;
  final BigInt timestamp;
  final bool isVerified;

  const FlutterPresenceRecord({
    required this.pubkeyHex,
    required this.connectionWords,
    required this.timestamp,
    required this.isVerified,
  });

  @override
  int get hashCode => pubkeyHex.hashCode ^ connectionWords.hashCode ^ timestamp.hashCode ^ isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPresenceRecord &&
          runtimeType == other.runtimeType &&
          pubkeyHex == other.pubkeyHex &&
          connectionWords == other.connectionWords &&
          timestamp == other.timestamp &&
          isVerified == other.isVerified;
}

/// Presence status for a peer (online/offline/unknown)
class FlutterPresenceStatus {
  final String peerId;
  final String status;
  final PlatformInt64 lastSeen;

  const FlutterPresenceStatus({
    required this.peerId,
    required this.status,
    required this.lastSeen,
  });

  @override
  int get hashCode => peerId.hashCode ^ status.hashCode ^ lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPresenceStatus &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          status == other.status &&
          lastSeen == other.lastSeen;
}

class FlutterReaction {
  final String emoji;
  final int count;
  final bool userReacted;
  final List<String> peerIds;

  const FlutterReaction({
    required this.emoji,
    required this.count,
    required this.userReacted,
    required this.peerIds,
  });

  @override
  int get hashCode => emoji.hashCode ^ count.hashCode ^ userReacted.hashCode ^ peerIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterReaction &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          count == other.count &&
          userReacted == other.userReacted &&
          peerIds == other.peerIds;
}

/// Identity recovery preview/result
class FlutterRecoveredIdentity {
  final String fourWords;
  final String pubkeyHex;

  const FlutterRecoveredIdentity({
    required this.fourWords,
    required this.pubkeyHex,
  });

  @override
  int get hashCode => fourWords.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRecoveredIdentity &&
          runtimeType == other.runtimeType &&
          fourWords == other.fourWords &&
          pubkeyHex == other.pubkeyHex;
}

/// Session information
class FlutterSessionInfo {
  final String sessionId;
  final String fourWords;
  final String displayName;

  /// Hex-encoded ML-DSA-87 public key (the user's cryptographic identity)
  final String pubkeyHex;

  const FlutterSessionInfo({
    required this.sessionId,
    required this.fourWords,
    required this.displayName,
    required this.pubkeyHex,
  });

  @override
  int get hashCode => sessionId.hashCode ^ fourWords.hashCode ^ displayName.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSessionInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          fourWords == other.fourWords &&
          displayName == other.displayName &&
          pubkeyHex == other.pubkeyHex;
}

/// User profile information
class FlutterUserProfile {
  final String fourWords;
  final String displayName;
  final String deviceName;
  final String deviceType;

  const FlutterUserProfile({
    required this.fourWords,
    required this.displayName,
    required this.deviceName,
    required this.deviceType,
  });

  @override
  int get hashCode => fourWords.hashCode ^ displayName.hashCode ^ deviceName.hashCode ^ deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterUserProfile &&
          runtimeType == other.runtimeType &&
          fourWords == other.fourWords &&
          displayName == other.displayName &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType;
}

/// Vault information
class FlutterVaultInfo {
  final String fourWords;
  final String displayName;
  final BigInt createdAt;
  final BigInt lastAccessed;
  final BigInt sizeBytes;

  const FlutterVaultInfo({
    required this.fourWords,
    required this.displayName,
    required this.createdAt,
    required this.lastAccessed,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      fourWords.hashCode ^ displayName.hashCode ^ createdAt.hashCode ^ lastAccessed.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterVaultInfo &&
          runtimeType == other.runtimeType &&
          fourWords == other.fourWords &&
          displayName == other.displayName &&
          createdAt == other.createdAt &&
          lastAccessed == other.lastAccessed &&
          sizeBytes == other.sizeBytes;
}
