import Foundation
import CommunitasKit

/// Bridge between the Rust WebRTC layer (via UniFFI) and the Swift UI
/// This service subscribes to WebRTC events from the Rust core and forwards them to CallStateManager
@MainActor
public final class WebRTCEventBridge: ObservableObject {

    // MARK: - Singleton

    public static let shared = WebRTCEventBridge()

    // MARK: - Properties

    private let callManager: CallStateManager
    public private(set) var isListening = false

    // MARK: - Initialization

    private init() {
        self.callManager = CallStateManager.shared
    }

    /// Testing initializer that allows injecting a custom CallStateManager
    internal init(callManager: CallStateManager) {
        self.callManager = callManager
    }

    // MARK: - Event Listening

    /// Start listening for WebRTC events from the Rust layer
    /// Call this once the client is initialized
    public func startListening(client: CommunitasClient?) {
        guard !isListening else { return }
        isListening = true

        // In a real implementation, this would set up a callback/listener
        // with the Rust WebRTC layer via UniFFI
        // For now, we'll provide methods that the client can call
        print("[WebRTCEventBridge] Started listening for WebRTC events")
    }

    /// Stop listening for WebRTC events
    public func stopListening() {
        isListening = false
        print("[WebRTCEventBridge] Stopped listening for WebRTC events")
    }

    // MARK: - Event Handlers (Called from Rust layer)

    /// Handle call state change event from Rust
    public func onCallStateChanged(callId: String, state: String) {
        let event = WebRTCEvent.callStateChanged(callId: callId, state: state)
        callManager.handleWebRTCEvent(event)
    }

    /// Handle participant joined event from Rust
    public func onParticipantJoined(
        callId: String,
        participantId: String,
        fourWords: String,
        displayName: String?
    ) {
        let event = WebRTCEvent.participantJoined(
            callId: callId,
            participantId: participantId,
            fourWords: fourWords,
            displayName: displayName
        )
        callManager.handleWebRTCEvent(event)
    }

    /// Handle participant left event from Rust
    public func onParticipantLeft(callId: String, participantId: String) {
        let event = WebRTCEvent.participantLeft(callId: callId, participantId: participantId)
        callManager.handleWebRTCEvent(event)
    }

    /// Handle participant media changed event from Rust
    public func onParticipantMediaChanged(
        callId: String,
        participantId: String,
        videoEnabled: Bool,
        audioEnabled: Bool
    ) {
        let event = WebRTCEvent.participantMediaChanged(
            callId: callId,
            participantId: participantId,
            videoEnabled: videoEnabled,
            audioEnabled: audioEnabled
        )
        callManager.handleWebRTCEvent(event)
    }

    /// Handle call quality changed event from Rust
    public func onQualityChanged(callId: String, quality: String) {
        let event = WebRTCEvent.qualityChanged(callId: callId, quality: quality)
        callManager.handleWebRTCEvent(event)
    }

    /// Handle error event from Rust
    public func onError(callId: String, message: String) {
        let event = WebRTCEvent.error(callId: callId, message: message)
        callManager.handleWebRTCEvent(event)
    }

    /// Handle incoming call event from Rust
    public func onIncomingCall(
        callId: String,
        callerFourWords: String,
        callerDisplayName: String?,
        hasVideo: Bool
    ) {
        let event = WebRTCEvent.incomingCall(
            callId: callId,
            callerFourWords: callerFourWords,
            callerDisplayName: callerDisplayName,
            hasVideo: hasVideo
        )
        callManager.handleWebRTCEvent(event)
    }

    /// Handle call ended event from Rust
    public func onCallEnded(callId: String, reason: String) {
        let event = WebRTCEvent.callEnded(callId: callId, reason: reason)
        callManager.handleWebRTCEvent(event)
    }
}

// MARK: - Protocol for Rust Callback (Future UniFFI Integration)

/// Protocol that the Rust layer will implement to send events to Swift
/// This will be generated by UniFFI in the future
/// Marked @MainActor for Swift 6 concurrency safety
@MainActor
protocol WebRTCEventListener {
    func onCallStateChanged(callId: String, state: String)
    func onParticipantJoined(callId: String, participantId: String, fourWords: String, displayName: String?)
    func onParticipantLeft(callId: String, participantId: String)
    func onParticipantMediaChanged(callId: String, participantId: String, videoEnabled: Bool, audioEnabled: Bool)
    func onQualityChanged(callId: String, quality: String)
    func onError(callId: String, message: String)
    func onIncomingCall(callId: String, callerFourWords: String, callerDisplayName: String?, hasVideo: Bool)
    func onCallEnded(callId: String, reason: String)
}

// MARK: - WebRTCEventBridge conforms to WebRTCEventListener

extension WebRTCEventBridge: WebRTCEventListener {}
