// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'flutter_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `execute_command`, `execute_query`, `get_or_init_auth`, `to_dart_error`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterDiskType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Generate a random four-word identity
Future<String> generateIdWords() =>
    CommunitasRust.instance.api.crateFlutterApiGenerateIdWords();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CommunitasApi>>
abstract class CommunitasApi implements RustOpaqueInterface {
  /// Create a new vault with the given identity
  Future<String> authCreateVault(
      {required String fourWords,
      required String displayName,
      required String password});

  /// Delete a vault
  Future<void> authDeleteVault(
      {required String fourWords, required String password});

  /// Get the current session info
  Future<FlutterSessionInfo?> authGetCurrentSession();

  /// List all available vaults
  Future<List<FlutterVaultInfo>> authListVaults();

  /// Login to an existing vault
  Future<FlutterSessionInfo> authLogin(
      {required String fourWords, required String password});

  /// Logout from the current session
  Future<void> authLogout();

  /// Check if a vault exists
  Future<bool> authVaultExists({required String fourWords});

  /// Initialize the API with the given identity and storage path
  ///
  /// This creates a new CommunitasApp instance and returns the API wrapper.
  /// Returns an error string if initialization fails, or the API on success.
  static Future<CommunitasApi> create(
          {required String fourWords,
          required String displayName,
          required String deviceName,
          required String storagePath}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiCreate(
          fourWords: fourWords,
          displayName: displayName,
          deviceName: deviceName,
          storagePath: storagePath);

  /// Add a member to an entity
  Future<List<FlutterEvent>> entityAddMember(
      {required FlutterEntityType entityType,
      required String entityId,
      required String memberId,
      required String role});

  /// Create a new entity
  Future<List<FlutterEvent>> entityCreate(
      {required String name,
      required FlutterEntityType entityType,
      String? description,
      String? parentOrgId});

  /// Get an entity by ID
  Future<FlutterEntity> entityGet({required String entityId});

  /// List all entities
  Future<List<FlutterEntity>> entityList();

  /// List entities by type
  Future<List<FlutterEntity>> entityListByType(
      {required FlutterEntityType entityType});

  /// Remove a member from an entity
  Future<List<FlutterEvent>> entityRemoveMember(
      {required FlutterEntityType entityType,
      required String entityId,
      required String memberId});

  /// Get the current user profile
  Future<FlutterUserProfile> getProfile();

  /// Connect to a peer by four words
  Future<List<FlutterEvent>> gossipConnectToPeer({required String fourWords});

  /// Get network information
  Future<FlutterNetworkInfo> gossipGetNetworkInfo();

  /// Start the gossip network
  Future<List<FlutterEvent>> gossipStart({int? port});

  /// Stop the gossip network
  Future<List<FlutterEvent>> gossipStop();

  /// Accept an invite
  Future<List<FlutterEvent>> inviteAccept({required String inviteId});

  /// Create an invite
  Future<List<FlutterEvent>> inviteCreate(
      {required String recipientId,
      required FlutterEntityType entityType,
      required String entityId,
      required String role,
      String? message});

  /// Reject an invite
  Future<List<FlutterEvent>> inviteReject({required String inviteId});

  /// Revoke an invite (sender only)
  Future<List<FlutterEvent>> inviteRevoke({required String inviteId});

  /// Send a message to an entity
  Future<List<FlutterEvent>> messageSend(
      {required String entityId,
      required FlutterEntityType entityType,
      required String text,
      String? replyToId});

  /// Update display name
  Future<List<FlutterEvent>> updateDisplayName({required String displayName});
}

/// Entity information
class FlutterEntity {
  final String id;
  final String name;
  final FlutterEntityType entityType;
  final String? description;
  final String createdBy;
  final PlatformInt64 createdAt;
  final BigInt memberCount;
  final String? parentOrgId;
  final String? networkFourWords;
  final bool isLocalOnly;

  const FlutterEntity({
    required this.id,
    required this.name,
    required this.entityType,
    this.description,
    required this.createdBy,
    required this.createdAt,
    required this.memberCount,
    this.parentOrgId,
    this.networkFourWords,
    required this.isLocalOnly,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      entityType.hashCode ^
      description.hashCode ^
      createdBy.hashCode ^
      createdAt.hashCode ^
      memberCount.hashCode ^
      parentOrgId.hashCode ^
      networkFourWords.hashCode ^
      isLocalOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          entityType == other.entityType &&
          description == other.description &&
          createdBy == other.createdBy &&
          createdAt == other.createdAt &&
          memberCount == other.memberCount &&
          parentOrgId == other.parentOrgId &&
          networkFourWords == other.networkFourWords &&
          isLocalOnly == other.isLocalOnly;
}

/// Entity type enumeration
enum FlutterEntityType {
  group,
  channel,
  project,
  organisation,
  person,
  ;
}

@freezed
sealed class FlutterEvent with _$FlutterEvent {
  const FlutterEvent._();

  const factory FlutterEvent.networkingStarted({
    required String address,
  }) = FlutterEvent_NetworkingStarted;
  const factory FlutterEvent.networkingStopped() =
      FlutterEvent_NetworkingStopped;
  const factory FlutterEvent.peerConnected({
    required String peerId,
  }) = FlutterEvent_PeerConnected;
  const factory FlutterEvent.peerDisconnected({
    required String peerId,
  }) = FlutterEvent_PeerDisconnected;
  const factory FlutterEvent.entityCreated({
    required String entityId,
  }) = FlutterEvent_EntityCreated;
  const factory FlutterEvent.entityUpdated({
    required String entityId,
  }) = FlutterEvent_EntityUpdated;
  const factory FlutterEvent.messageSent({
    required String messageId,
    required String entityId,
  }) = FlutterEvent_MessageSent;
  const factory FlutterEvent.messageReceived({
    required String messageId,
    required String entityId,
  }) = FlutterEvent_MessageReceived;
  const factory FlutterEvent.inviteCreated({
    required String inviteId,
  }) = FlutterEvent_InviteCreated;
  const factory FlutterEvent.inviteAccepted({
    required String inviteId,
  }) = FlutterEvent_InviteAccepted;
  const factory FlutterEvent.fileWritten({
    required String entityId,
    required String path,
  }) = FlutterEvent_FileWritten;
  const factory FlutterEvent.fileDeleted({
    required String entityId,
    required String path,
  }) = FlutterEvent_FileDeleted;
  const factory FlutterEvent.error({
    required String code,
    required String message,
  }) = FlutterEvent_Error;
}

/// Network status information
class FlutterNetworkInfo {
  final bool isActive;
  final int? boundPort;
  final int peerCount;
  final String? externalAddress;
  final bool bootstrapConnected;

  const FlutterNetworkInfo({
    required this.isActive,
    this.boundPort,
    required this.peerCount,
    this.externalAddress,
    required this.bootstrapConnected,
  });

  @override
  int get hashCode =>
      isActive.hashCode ^
      boundPort.hashCode ^
      peerCount.hashCode ^
      externalAddress.hashCode ^
      bootstrapConnected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterNetworkInfo &&
          runtimeType == other.runtimeType &&
          isActive == other.isActive &&
          boundPort == other.boundPort &&
          peerCount == other.peerCount &&
          externalAddress == other.externalAddress &&
          bootstrapConnected == other.bootstrapConnected;
}

/// Session information
class FlutterSessionInfo {
  final String sessionId;
  final String fourWords;
  final String displayName;

  const FlutterSessionInfo({
    required this.sessionId,
    required this.fourWords,
    required this.displayName,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ fourWords.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSessionInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          fourWords == other.fourWords &&
          displayName == other.displayName;
}

/// User profile information
class FlutterUserProfile {
  final String fourWords;
  final String displayName;
  final String deviceName;
  final String deviceType;

  const FlutterUserProfile({
    required this.fourWords,
    required this.displayName,
    required this.deviceName,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      fourWords.hashCode ^
      displayName.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterUserProfile &&
          runtimeType == other.runtimeType &&
          fourWords == other.fourWords &&
          displayName == other.displayName &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType;
}

/// Vault information
class FlutterVaultInfo {
  final String fourWords;
  final String displayName;
  final BigInt createdAt;
  final BigInt lastAccessed;
  final BigInt sizeBytes;

  const FlutterVaultInfo({
    required this.fourWords,
    required this.displayName,
    required this.createdAt,
    required this.lastAccessed,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      fourWords.hashCode ^
      displayName.hashCode ^
      createdAt.hashCode ^
      lastAccessed.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterVaultInfo &&
          runtimeType == other.runtimeType &&
          fourWords == other.fourWords &&
          displayName == other.displayName &&
          createdAt == other.createdAt &&
          lastAccessed == other.lastAccessed &&
          sizeBytes == other.sizeBytes;
}
