// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'flutter_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CommunitasApiPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi;



                  @protected CommunitasApi dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(dynamic raw);

@protected CommunitasApi dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(dynamic raw);

@protected CommunitasApi dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected bool dco_decode_box_autoadd_bool(dynamic raw);

@protected FlutterPresenceRecord dco_decode_box_autoadd_flutter_presence_record(dynamic raw);

@protected FlutterSessionInfo dco_decode_box_autoadd_flutter_session_info(dynamic raw);

@protected PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

@protected int dco_decode_box_autoadd_u_16(dynamic raw);

@protected int dco_decode_box_autoadd_u_32(dynamic raw);

@protected BigInt dco_decode_box_autoadd_u_64(dynamic raw);

@protected FlutterContact dco_decode_flutter_contact(dynamic raw);

@protected FlutterDiskStats dco_decode_flutter_disk_stats(dynamic raw);

@protected FlutterDiskType dco_decode_flutter_disk_type(dynamic raw);

@protected FlutterEntity dco_decode_flutter_entity(dynamic raw);

@protected FlutterEntityType dco_decode_flutter_entity_type(dynamic raw);

@protected FlutterEvent dco_decode_flutter_event(dynamic raw);

@protected FlutterFileInfo dco_decode_flutter_file_info(dynamic raw);

@protected FlutterKanbanBoard dco_decode_flutter_kanban_board(dynamic raw);

@protected FlutterKanbanCard dco_decode_flutter_kanban_card(dynamic raw);

@protected FlutterKanbanColumn dco_decode_flutter_kanban_column(dynamic raw);

@protected FlutterMessage dco_decode_flutter_message(dynamic raw);

@protected FlutterNetworkInfo dco_decode_flutter_network_info(dynamic raw);

@protected FlutterPresenceRecord dco_decode_flutter_presence_record(dynamic raw);

@protected FlutterPresenceStatus dco_decode_flutter_presence_status(dynamic raw);

@protected FlutterReaction dco_decode_flutter_reaction(dynamic raw);

@protected FlutterRecoveredIdentity dco_decode_flutter_recovered_identity(dynamic raw);

@protected FlutterSessionInfo dco_decode_flutter_session_info(dynamic raw);

@protected FlutterUserProfile dco_decode_flutter_user_profile(dynamic raw);

@protected FlutterVaultInfo dco_decode_flutter_vault_info(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<FlutterContact> dco_decode_list_flutter_contact(dynamic raw);

@protected List<FlutterEntity> dco_decode_list_flutter_entity(dynamic raw);

@protected List<FlutterEvent> dco_decode_list_flutter_event(dynamic raw);

@protected List<FlutterFileInfo> dco_decode_list_flutter_file_info(dynamic raw);

@protected List<FlutterKanbanBoard> dco_decode_list_flutter_kanban_board(dynamic raw);

@protected List<FlutterKanbanCard> dco_decode_list_flutter_kanban_card(dynamic raw);

@protected List<FlutterKanbanColumn> dco_decode_list_flutter_kanban_column(dynamic raw);

@protected List<FlutterMessage> dco_decode_list_flutter_message(dynamic raw);

@protected List<FlutterReaction> dco_decode_list_flutter_reaction(dynamic raw);

@protected List<FlutterVaultInfo> dco_decode_list_flutter_vault_info(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

@protected FlutterPresenceRecord? dco_decode_opt_box_autoadd_flutter_presence_record(dynamic raw);

@protected FlutterSessionInfo? dco_decode_opt_box_autoadd_flutter_session_info(dynamic raw);

@protected PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

@protected int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

@protected int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

@protected BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

@protected int dco_decode_u_16(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected CommunitasApi sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(SseDeserializer deserializer);

@protected CommunitasApi sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(SseDeserializer deserializer);

@protected CommunitasApi sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

@protected FlutterPresenceRecord sse_decode_box_autoadd_flutter_presence_record(SseDeserializer deserializer);

@protected FlutterSessionInfo sse_decode_box_autoadd_flutter_session_info(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

@protected FlutterContact sse_decode_flutter_contact(SseDeserializer deserializer);

@protected FlutterDiskStats sse_decode_flutter_disk_stats(SseDeserializer deserializer);

@protected FlutterDiskType sse_decode_flutter_disk_type(SseDeserializer deserializer);

@protected FlutterEntity sse_decode_flutter_entity(SseDeserializer deserializer);

@protected FlutterEntityType sse_decode_flutter_entity_type(SseDeserializer deserializer);

@protected FlutterEvent sse_decode_flutter_event(SseDeserializer deserializer);

@protected FlutterFileInfo sse_decode_flutter_file_info(SseDeserializer deserializer);

@protected FlutterKanbanBoard sse_decode_flutter_kanban_board(SseDeserializer deserializer);

@protected FlutterKanbanCard sse_decode_flutter_kanban_card(SseDeserializer deserializer);

@protected FlutterKanbanColumn sse_decode_flutter_kanban_column(SseDeserializer deserializer);

@protected FlutterMessage sse_decode_flutter_message(SseDeserializer deserializer);

@protected FlutterNetworkInfo sse_decode_flutter_network_info(SseDeserializer deserializer);

@protected FlutterPresenceRecord sse_decode_flutter_presence_record(SseDeserializer deserializer);

@protected FlutterPresenceStatus sse_decode_flutter_presence_status(SseDeserializer deserializer);

@protected FlutterReaction sse_decode_flutter_reaction(SseDeserializer deserializer);

@protected FlutterRecoveredIdentity sse_decode_flutter_recovered_identity(SseDeserializer deserializer);

@protected FlutterSessionInfo sse_decode_flutter_session_info(SseDeserializer deserializer);

@protected FlutterUserProfile sse_decode_flutter_user_profile(SseDeserializer deserializer);

@protected FlutterVaultInfo sse_decode_flutter_vault_info(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<FlutterContact> sse_decode_list_flutter_contact(SseDeserializer deserializer);

@protected List<FlutterEntity> sse_decode_list_flutter_entity(SseDeserializer deserializer);

@protected List<FlutterEvent> sse_decode_list_flutter_event(SseDeserializer deserializer);

@protected List<FlutterFileInfo> sse_decode_list_flutter_file_info(SseDeserializer deserializer);

@protected List<FlutterKanbanBoard> sse_decode_list_flutter_kanban_board(SseDeserializer deserializer);

@protected List<FlutterKanbanCard> sse_decode_list_flutter_kanban_card(SseDeserializer deserializer);

@protected List<FlutterKanbanColumn> sse_decode_list_flutter_kanban_column(SseDeserializer deserializer);

@protected List<FlutterMessage> sse_decode_list_flutter_message(SseDeserializer deserializer);

@protected List<FlutterReaction> sse_decode_list_flutter_reaction(SseDeserializer deserializer);

@protected List<FlutterVaultInfo> sse_decode_list_flutter_vault_info(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

@protected FlutterPresenceRecord? sse_decode_opt_box_autoadd_flutter_presence_record(SseDeserializer deserializer);

@protected FlutterSessionInfo? sse_decode_opt_box_autoadd_flutter_session_info(SseDeserializer deserializer);

@protected PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

@protected BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(CommunitasApi self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(CommunitasApi self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(CommunitasApi self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_flutter_presence_record(FlutterPresenceRecord self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_flutter_session_info(FlutterSessionInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_flutter_contact(FlutterContact self, SseSerializer serializer);

@protected void sse_encode_flutter_disk_stats(FlutterDiskStats self, SseSerializer serializer);

@protected void sse_encode_flutter_disk_type(FlutterDiskType self, SseSerializer serializer);

@protected void sse_encode_flutter_entity(FlutterEntity self, SseSerializer serializer);

@protected void sse_encode_flutter_entity_type(FlutterEntityType self, SseSerializer serializer);

@protected void sse_encode_flutter_event(FlutterEvent self, SseSerializer serializer);

@protected void sse_encode_flutter_file_info(FlutterFileInfo self, SseSerializer serializer);

@protected void sse_encode_flutter_kanban_board(FlutterKanbanBoard self, SseSerializer serializer);

@protected void sse_encode_flutter_kanban_card(FlutterKanbanCard self, SseSerializer serializer);

@protected void sse_encode_flutter_kanban_column(FlutterKanbanColumn self, SseSerializer serializer);

@protected void sse_encode_flutter_message(FlutterMessage self, SseSerializer serializer);

@protected void sse_encode_flutter_network_info(FlutterNetworkInfo self, SseSerializer serializer);

@protected void sse_encode_flutter_presence_record(FlutterPresenceRecord self, SseSerializer serializer);

@protected void sse_encode_flutter_presence_status(FlutterPresenceStatus self, SseSerializer serializer);

@protected void sse_encode_flutter_reaction(FlutterReaction self, SseSerializer serializer);

@protected void sse_encode_flutter_recovered_identity(FlutterRecoveredIdentity self, SseSerializer serializer);

@protected void sse_encode_flutter_session_info(FlutterSessionInfo self, SseSerializer serializer);

@protected void sse_encode_flutter_user_profile(FlutterUserProfile self, SseSerializer serializer);

@protected void sse_encode_flutter_vault_info(FlutterVaultInfo self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_contact(List<FlutterContact> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_entity(List<FlutterEntity> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_event(List<FlutterEvent> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_file_info(List<FlutterFileInfo> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_kanban_board(List<FlutterKanbanBoard> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_kanban_card(List<FlutterKanbanCard> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_kanban_column(List<FlutterKanbanColumn> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_message(List<FlutterMessage> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_reaction(List<FlutterReaction> self, SseSerializer serializer);

@protected void sse_encode_list_flutter_vault_info(List<FlutterVaultInfo> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_flutter_presence_record(FlutterPresenceRecord? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_flutter_session_info(FlutterSessionInfo? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(ptr);
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(int ptr);
        }
        