// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'flutter_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class CommunitasRust extends BaseEntrypoint<CommunitasRustApi,
    CommunitasRustApiImpl, CommunitasRustWire> {
  @internal
  static final instance = CommunitasRust._();

  CommunitasRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    CommunitasRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required CommunitasRustApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<CommunitasRustApiImpl, CommunitasRustWire>
      get apiImplConstructor => CommunitasRustApiImpl.new;

  @override
  WireConstructor<CommunitasRustWire> get wireConstructor =>
      CommunitasRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1887355562;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'communitas_bindings',
    ioDirectory: '../communitas-bindings/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class CommunitasRustApi extends BaseApi {
  Future<String> crateFlutterApiCommunitasApiAuthCreateVault(
      {required CommunitasApi that,
      required String fourWords,
      required String displayName,
      required String password});

  Future<void> crateFlutterApiCommunitasApiAuthDeleteVault(
      {required CommunitasApi that,
      required String fourWords,
      required String password});

  Future<FlutterSessionInfo?> crateFlutterApiCommunitasApiAuthGetCurrentSession(
      {required CommunitasApi that});

  Future<List<FlutterVaultInfo>> crateFlutterApiCommunitasApiAuthListVaults(
      {required CommunitasApi that});

  Future<FlutterSessionInfo> crateFlutterApiCommunitasApiAuthLogin(
      {required CommunitasApi that,
      required String fourWords,
      required String password});

  Future<void> crateFlutterApiCommunitasApiAuthLogout(
      {required CommunitasApi that});

  Future<bool> crateFlutterApiCommunitasApiAuthVaultExists(
      {required CommunitasApi that, required String fourWords});

  Future<CommunitasApi> crateFlutterApiCommunitasApiCreate(
      {required String fourWords,
      required String displayName,
      required String deviceName,
      required String storagePath});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityAddMember(
      {required CommunitasApi that,
      required FlutterEntityType entityType,
      required String entityId,
      required String memberId,
      required String role});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityCreate(
      {required CommunitasApi that,
      required String name,
      required FlutterEntityType entityType,
      String? description,
      String? parentOrgId});

  Future<FlutterEntity> crateFlutterApiCommunitasApiEntityGet(
      {required CommunitasApi that, required String entityId});

  Future<List<FlutterEntity>> crateFlutterApiCommunitasApiEntityList(
      {required CommunitasApi that});

  Future<List<FlutterEntity>> crateFlutterApiCommunitasApiEntityListByType(
      {required CommunitasApi that, required FlutterEntityType entityType});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityRemoveMember(
      {required CommunitasApi that,
      required FlutterEntityType entityType,
      required String entityId,
      required String memberId});

  Future<FlutterUserProfile> crateFlutterApiCommunitasApiGetProfile(
      {required CommunitasApi that});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipConnectToPeer(
      {required CommunitasApi that, required String fourWords});

  Future<FlutterNetworkInfo> crateFlutterApiCommunitasApiGossipGetNetworkInfo(
      {required CommunitasApi that});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipStart(
      {required CommunitasApi that, int? port});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipStop(
      {required CommunitasApi that});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteAccept(
      {required CommunitasApi that, required String inviteId});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteCreate(
      {required CommunitasApi that,
      required String recipientId,
      required FlutterEntityType entityType,
      required String entityId,
      required String role,
      String? message});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteReject(
      {required CommunitasApi that, required String inviteId});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteRevoke(
      {required CommunitasApi that, required String inviteId});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiMessageSend(
      {required CommunitasApi that,
      required String entityId,
      required FlutterEntityType entityType,
      required String text,
      String? replyToId});

  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiUpdateDisplayName(
      {required CommunitasApi that, required String displayName});

  Future<String> crateFlutterApiGenerateIdWords();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CommunitasApi;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CommunitasApi;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CommunitasApiPtr;
}

class CommunitasRustApiImpl extends CommunitasRustApiImplPlatform
    implements CommunitasRustApi {
  CommunitasRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateFlutterApiCommunitasApiAuthCreateVault(
      {required CommunitasApi that,
      required String fourWords,
      required String displayName,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(fourWords);
        var arg2 = cst_encode_String(displayName);
        var arg3 = cst_encode_String(password);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_create_vault(
            port_, arg0, arg1, arg2, arg3);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthCreateVaultConstMeta,
      argValues: [that, fourWords, displayName, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthCreateVaultConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_create_vault",
        argNames: ["that", "fourWords", "displayName", "password"],
      );

  @override
  Future<void> crateFlutterApiCommunitasApiAuthDeleteVault(
      {required CommunitasApi that,
      required String fourWords,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(fourWords);
        var arg2 = cst_encode_String(password);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_delete_vault(
            port_, arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthDeleteVaultConstMeta,
      argValues: [that, fourWords, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthDeleteVaultConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_delete_vault",
        argNames: ["that", "fourWords", "password"],
      );

  @override
  Future<FlutterSessionInfo?> crateFlutterApiCommunitasApiAuthGetCurrentSession(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire
            .wire__crate__flutter_api__CommunitasApi_auth_get_current_session(
                port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_opt_box_autoadd_flutter_session_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthGetCurrentSessionConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateFlutterApiCommunitasApiAuthGetCurrentSessionConstMeta =>
          const TaskConstMeta(
            debugName: "CommunitasApi_auth_get_current_session",
            argNames: ["that"],
          );

  @override
  Future<List<FlutterVaultInfo>> crateFlutterApiCommunitasApiAuthListVaults(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_list_vaults(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_vault_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthListVaultsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthListVaultsConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_list_vaults",
        argNames: ["that"],
      );

  @override
  Future<FlutterSessionInfo> crateFlutterApiCommunitasApiAuthLogin(
      {required CommunitasApi that,
      required String fourWords,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(fourWords);
        var arg2 = cst_encode_String(password);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_login(
            port_, arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_flutter_session_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthLoginConstMeta,
      argValues: [that, fourWords, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthLoginConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_login",
        argNames: ["that", "fourWords", "password"],
      );

  @override
  Future<void> crateFlutterApiCommunitasApiAuthLogout(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_logout(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthLogoutConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthLogoutConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_logout",
        argNames: ["that"],
      );

  @override
  Future<bool> crateFlutterApiCommunitasApiAuthVaultExists(
      {required CommunitasApi that, required String fourWords}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(fourWords);
        return wire.wire__crate__flutter_api__CommunitasApi_auth_vault_exists(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiAuthVaultExistsConstMeta,
      argValues: [that, fourWords],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiAuthVaultExistsConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_auth_vault_exists",
        argNames: ["that", "fourWords"],
      );

  @override
  Future<CommunitasApi> crateFlutterApiCommunitasApiCreate(
      {required String fourWords,
      required String displayName,
      required String deviceName,
      required String storagePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(fourWords);
        var arg1 = cst_encode_String(displayName);
        var arg2 = cst_encode_String(deviceName);
        var arg3 = cst_encode_String(storagePath);
        return wire.wire__crate__flutter_api__CommunitasApi_create(
            port_, arg0, arg1, arg2, arg3);
      },
      codec: DcoCodec(
        decodeSuccessData:
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateFlutterApiCommunitasApiCreateConstMeta,
      argValues: [fourWords, displayName, deviceName, storagePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiCreateConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_create",
        argNames: ["fourWords", "displayName", "deviceName", "storagePath"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityAddMember(
      {required CommunitasApi that,
      required FlutterEntityType entityType,
      required String entityId,
      required String memberId,
      required String role}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_flutter_entity_type(entityType);
        var arg2 = cst_encode_String(entityId);
        var arg3 = cst_encode_String(memberId);
        var arg4 = cst_encode_String(role);
        return wire.wire__crate__flutter_api__CommunitasApi_entity_add_member(
            port_, arg0, arg1, arg2, arg3, arg4);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityAddMemberConstMeta,
      argValues: [that, entityType, entityId, memberId, role],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityAddMemberConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_add_member",
        argNames: ["that", "entityType", "entityId", "memberId", "role"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityCreate(
      {required CommunitasApi that,
      required String name,
      required FlutterEntityType entityType,
      String? description,
      String? parentOrgId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(name);
        var arg2 = cst_encode_flutter_entity_type(entityType);
        var arg3 = cst_encode_opt_String(description);
        var arg4 = cst_encode_opt_String(parentOrgId);
        return wire.wire__crate__flutter_api__CommunitasApi_entity_create(
            port_, arg0, arg1, arg2, arg3, arg4);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityCreateConstMeta,
      argValues: [that, name, entityType, description, parentOrgId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityCreateConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_create",
        argNames: ["that", "name", "entityType", "description", "parentOrgId"],
      );

  @override
  Future<FlutterEntity> crateFlutterApiCommunitasApiEntityGet(
      {required CommunitasApi that, required String entityId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(entityId);
        return wire.wire__crate__flutter_api__CommunitasApi_entity_get(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_flutter_entity,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityGetConstMeta,
      argValues: [that, entityId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityGetConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_get",
        argNames: ["that", "entityId"],
      );

  @override
  Future<List<FlutterEntity>> crateFlutterApiCommunitasApiEntityList(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire.wire__crate__flutter_api__CommunitasApi_entity_list(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_entity,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityListConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityListConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_list",
        argNames: ["that"],
      );

  @override
  Future<List<FlutterEntity>> crateFlutterApiCommunitasApiEntityListByType(
      {required CommunitasApi that, required FlutterEntityType entityType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_flutter_entity_type(entityType);
        return wire.wire__crate__flutter_api__CommunitasApi_entity_list_by_type(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_entity,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityListByTypeConstMeta,
      argValues: [that, entityType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityListByTypeConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_list_by_type",
        argNames: ["that", "entityType"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiEntityRemoveMember(
      {required CommunitasApi that,
      required FlutterEntityType entityType,
      required String entityId,
      required String memberId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_flutter_entity_type(entityType);
        var arg2 = cst_encode_String(entityId);
        var arg3 = cst_encode_String(memberId);
        return wire
            .wire__crate__flutter_api__CommunitasApi_entity_remove_member(
                port_, arg0, arg1, arg2, arg3);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiEntityRemoveMemberConstMeta,
      argValues: [that, entityType, entityId, memberId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiEntityRemoveMemberConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_entity_remove_member",
        argNames: ["that", "entityType", "entityId", "memberId"],
      );

  @override
  Future<FlutterUserProfile> crateFlutterApiCommunitasApiGetProfile(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire.wire__crate__flutter_api__CommunitasApi_get_profile(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_flutter_user_profile,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiGetProfileConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiGetProfileConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_get_profile",
        argNames: ["that"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipConnectToPeer(
      {required CommunitasApi that, required String fourWords}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(fourWords);
        return wire
            .wire__crate__flutter_api__CommunitasApi_gossip_connect_to_peer(
                port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiGossipConnectToPeerConstMeta,
      argValues: [that, fourWords],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiGossipConnectToPeerConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_gossip_connect_to_peer",
        argNames: ["that", "fourWords"],
      );

  @override
  Future<FlutterNetworkInfo> crateFlutterApiCommunitasApiGossipGetNetworkInfo(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire
            .wire__crate__flutter_api__CommunitasApi_gossip_get_network_info(
                port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_flutter_network_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiGossipGetNetworkInfoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateFlutterApiCommunitasApiGossipGetNetworkInfoConstMeta =>
          const TaskConstMeta(
            debugName: "CommunitasApi_gossip_get_network_info",
            argNames: ["that"],
          );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipStart(
      {required CommunitasApi that, int? port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_opt_box_autoadd_u_16(port);
        return wire.wire__crate__flutter_api__CommunitasApi_gossip_start(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiGossipStartConstMeta,
      argValues: [that, port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiGossipStartConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_gossip_start",
        argNames: ["that", "port"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiGossipStop(
      {required CommunitasApi that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        return wire.wire__crate__flutter_api__CommunitasApi_gossip_stop(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiGossipStopConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiGossipStopConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_gossip_stop",
        argNames: ["that"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteAccept(
      {required CommunitasApi that, required String inviteId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(inviteId);
        return wire.wire__crate__flutter_api__CommunitasApi_invite_accept(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiInviteAcceptConstMeta,
      argValues: [that, inviteId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiInviteAcceptConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_invite_accept",
        argNames: ["that", "inviteId"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteCreate(
      {required CommunitasApi that,
      required String recipientId,
      required FlutterEntityType entityType,
      required String entityId,
      required String role,
      String? message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(recipientId);
        var arg2 = cst_encode_flutter_entity_type(entityType);
        var arg3 = cst_encode_String(entityId);
        var arg4 = cst_encode_String(role);
        var arg5 = cst_encode_opt_String(message);
        return wire.wire__crate__flutter_api__CommunitasApi_invite_create(
            port_, arg0, arg1, arg2, arg3, arg4, arg5);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiInviteCreateConstMeta,
      argValues: [that, recipientId, entityType, entityId, role, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiInviteCreateConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_invite_create",
        argNames: [
          "that",
          "recipientId",
          "entityType",
          "entityId",
          "role",
          "message"
        ],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteReject(
      {required CommunitasApi that, required String inviteId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(inviteId);
        return wire.wire__crate__flutter_api__CommunitasApi_invite_reject(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiInviteRejectConstMeta,
      argValues: [that, inviteId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiInviteRejectConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_invite_reject",
        argNames: ["that", "inviteId"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiInviteRevoke(
      {required CommunitasApi that, required String inviteId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(inviteId);
        return wire.wire__crate__flutter_api__CommunitasApi_invite_revoke(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiInviteRevokeConstMeta,
      argValues: [that, inviteId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiInviteRevokeConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_invite_revoke",
        argNames: ["that", "inviteId"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiMessageSend(
      {required CommunitasApi that,
      required String entityId,
      required FlutterEntityType entityType,
      required String text,
      String? replyToId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(entityId);
        var arg2 = cst_encode_flutter_entity_type(entityType);
        var arg3 = cst_encode_String(text);
        var arg4 = cst_encode_opt_String(replyToId);
        return wire.wire__crate__flutter_api__CommunitasApi_message_send(
            port_, arg0, arg1, arg2, arg3, arg4);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiMessageSendConstMeta,
      argValues: [that, entityId, entityType, text, replyToId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiMessageSendConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_message_send",
        argNames: ["that", "entityId", "entityType", "text", "replyToId"],
      );

  @override
  Future<List<FlutterEvent>> crateFlutterApiCommunitasApiUpdateDisplayName(
      {required CommunitasApi that, required String displayName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
                that);
        var arg1 = cst_encode_String(displayName);
        return wire.wire__crate__flutter_api__CommunitasApi_update_display_name(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_flutter_event,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiCommunitasApiUpdateDisplayNameConstMeta,
      argValues: [that, displayName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiCommunitasApiUpdateDisplayNameConstMeta =>
      const TaskConstMeta(
        debugName: "CommunitasApi_update_display_name",
        argNames: ["that", "displayName"],
      );

  @override
  Future<String> crateFlutterApiGenerateIdWords() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__flutter_api__generate_id_words(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFlutterApiGenerateIdWordsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFlutterApiGenerateIdWordsConstMeta =>
      const TaskConstMeta(
        debugName: "generate_id_words",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CommunitasApi => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CommunitasApi => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi;

  @protected
  CommunitasApi
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CommunitasApi
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CommunitasApi
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterSessionInfo dco_decode_box_autoadd_flutter_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_session_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  FlutterEntity dco_decode_flutter_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return FlutterEntity(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      entityType: dco_decode_flutter_entity_type(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      createdBy: dco_decode_String(arr[4]),
      createdAt: dco_decode_i_64(arr[5]),
      memberCount: dco_decode_usize(arr[6]),
      parentOrgId: dco_decode_opt_String(arr[7]),
      networkFourWords: dco_decode_opt_String(arr[8]),
      isLocalOnly: dco_decode_bool(arr[9]),
    );
  }

  @protected
  FlutterEntityType dco_decode_flutter_entity_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterEntityType.values[raw as int];
  }

  @protected
  FlutterEvent dco_decode_flutter_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FlutterEvent_NetworkingStarted(
          address: dco_decode_String(raw[1]),
        );
      case 1:
        return const FlutterEvent_NetworkingStopped();
      case 2:
        return FlutterEvent_PeerConnected(
          peerId: dco_decode_String(raw[1]),
        );
      case 3:
        return FlutterEvent_PeerDisconnected(
          peerId: dco_decode_String(raw[1]),
        );
      case 4:
        return FlutterEvent_EntityCreated(
          entityId: dco_decode_String(raw[1]),
        );
      case 5:
        return FlutterEvent_EntityUpdated(
          entityId: dco_decode_String(raw[1]),
        );
      case 6:
        return FlutterEvent_MessageSent(
          messageId: dco_decode_String(raw[1]),
          entityId: dco_decode_String(raw[2]),
        );
      case 7:
        return FlutterEvent_MessageReceived(
          messageId: dco_decode_String(raw[1]),
          entityId: dco_decode_String(raw[2]),
        );
      case 8:
        return FlutterEvent_InviteCreated(
          inviteId: dco_decode_String(raw[1]),
        );
      case 9:
        return FlutterEvent_InviteAccepted(
          inviteId: dco_decode_String(raw[1]),
        );
      case 10:
        return FlutterEvent_FileWritten(
          entityId: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
        );
      case 11:
        return FlutterEvent_FileDeleted(
          entityId: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
        );
      case 12:
        return FlutterEvent_Error(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  FlutterNetworkInfo dco_decode_flutter_network_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterNetworkInfo(
      isActive: dco_decode_bool(arr[0]),
      boundPort: dco_decode_opt_box_autoadd_u_16(arr[1]),
      peerCount: dco_decode_u_32(arr[2]),
      externalAddress: dco_decode_opt_String(arr[3]),
      bootstrapConnected: dco_decode_bool(arr[4]),
    );
  }

  @protected
  FlutterSessionInfo dco_decode_flutter_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FlutterSessionInfo(
      sessionId: dco_decode_String(arr[0]),
      fourWords: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
    );
  }

  @protected
  FlutterUserProfile dco_decode_flutter_user_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterUserProfile(
      fourWords: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      deviceType: dco_decode_String(arr[3]),
    );
  }

  @protected
  FlutterVaultInfo dco_decode_flutter_vault_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterVaultInfo(
      fourWords: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      createdAt: dco_decode_u_64(arr[2]),
      lastAccessed: dco_decode_u_64(arr[3]),
      sizeBytes: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<FlutterEntity> dco_decode_list_flutter_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_entity).toList();
  }

  @protected
  List<FlutterEvent> dco_decode_list_flutter_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_event).toList();
  }

  @protected
  List<FlutterVaultInfo> dco_decode_list_flutter_vault_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_vault_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FlutterSessionInfo? dco_decode_opt_box_autoadd_flutter_session_info(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_flutter_session_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CommunitasApi
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CommunitasApi
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CommunitasApi
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CommunitasApiImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterSessionInfo sse_decode_box_autoadd_flutter_session_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_session_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  FlutterEntity sse_decode_flutter_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_entityType = sse_decode_flutter_entity_type(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_createdBy = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_memberCount = sse_decode_usize(deserializer);
    var var_parentOrgId = sse_decode_opt_String(deserializer);
    var var_networkFourWords = sse_decode_opt_String(deserializer);
    var var_isLocalOnly = sse_decode_bool(deserializer);
    return FlutterEntity(
        id: var_id,
        name: var_name,
        entityType: var_entityType,
        description: var_description,
        createdBy: var_createdBy,
        createdAt: var_createdAt,
        memberCount: var_memberCount,
        parentOrgId: var_parentOrgId,
        networkFourWords: var_networkFourWords,
        isLocalOnly: var_isLocalOnly);
  }

  @protected
  FlutterEntityType sse_decode_flutter_entity_type(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterEntityType.values[inner];
  }

  @protected
  FlutterEvent sse_decode_flutter_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_address = sse_decode_String(deserializer);
        return FlutterEvent_NetworkingStarted(address: var_address);
      case 1:
        return const FlutterEvent_NetworkingStopped();
      case 2:
        var var_peerId = sse_decode_String(deserializer);
        return FlutterEvent_PeerConnected(peerId: var_peerId);
      case 3:
        var var_peerId = sse_decode_String(deserializer);
        return FlutterEvent_PeerDisconnected(peerId: var_peerId);
      case 4:
        var var_entityId = sse_decode_String(deserializer);
        return FlutterEvent_EntityCreated(entityId: var_entityId);
      case 5:
        var var_entityId = sse_decode_String(deserializer);
        return FlutterEvent_EntityUpdated(entityId: var_entityId);
      case 6:
        var var_messageId = sse_decode_String(deserializer);
        var var_entityId = sse_decode_String(deserializer);
        return FlutterEvent_MessageSent(
            messageId: var_messageId, entityId: var_entityId);
      case 7:
        var var_messageId = sse_decode_String(deserializer);
        var var_entityId = sse_decode_String(deserializer);
        return FlutterEvent_MessageReceived(
            messageId: var_messageId, entityId: var_entityId);
      case 8:
        var var_inviteId = sse_decode_String(deserializer);
        return FlutterEvent_InviteCreated(inviteId: var_inviteId);
      case 9:
        var var_inviteId = sse_decode_String(deserializer);
        return FlutterEvent_InviteAccepted(inviteId: var_inviteId);
      case 10:
        var var_entityId = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return FlutterEvent_FileWritten(entityId: var_entityId, path: var_path);
      case 11:
        var var_entityId = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return FlutterEvent_FileDeleted(entityId: var_entityId, path: var_path);
      case 12:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return FlutterEvent_Error(code: var_code, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  FlutterNetworkInfo sse_decode_flutter_network_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isActive = sse_decode_bool(deserializer);
    var var_boundPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_peerCount = sse_decode_u_32(deserializer);
    var var_externalAddress = sse_decode_opt_String(deserializer);
    var var_bootstrapConnected = sse_decode_bool(deserializer);
    return FlutterNetworkInfo(
        isActive: var_isActive,
        boundPort: var_boundPort,
        peerCount: var_peerCount,
        externalAddress: var_externalAddress,
        bootstrapConnected: var_bootstrapConnected);
  }

  @protected
  FlutterSessionInfo sse_decode_flutter_session_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_fourWords = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return FlutterSessionInfo(
        sessionId: var_sessionId,
        fourWords: var_fourWords,
        displayName: var_displayName);
  }

  @protected
  FlutterUserProfile sse_decode_flutter_user_profile(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fourWords = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    return FlutterUserProfile(
        fourWords: var_fourWords,
        displayName: var_displayName,
        deviceName: var_deviceName,
        deviceType: var_deviceType);
  }

  @protected
  FlutterVaultInfo sse_decode_flutter_vault_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fourWords = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_lastAccessed = sse_decode_u_64(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    return FlutterVaultInfo(
        fourWords: var_fourWords,
        displayName: var_displayName,
        createdAt: var_createdAt,
        lastAccessed: var_lastAccessed,
        sizeBytes: var_sizeBytes);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<FlutterEntity> sse_decode_list_flutter_entity(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterEntity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_entity(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlutterEvent> sse_decode_list_flutter_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlutterVaultInfo> sse_decode_list_flutter_vault_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterVaultInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_vault_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FlutterSessionInfo? sse_decode_opt_box_autoadd_flutter_session_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flutter_session_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
      CommunitasApi raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as CommunitasApiImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
      CommunitasApi raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as CommunitasApiImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
      CommunitasApi raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as CommunitasApiImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_flutter_entity_type(FlutterEntityType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          CommunitasApi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CommunitasApiImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          CommunitasApi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CommunitasApiImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCommunitasApi(
          CommunitasApi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CommunitasApiImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_session_info(
      FlutterSessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_session_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_flutter_entity(FlutterEntity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_flutter_entity_type(self.entityType, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_String(self.createdBy, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_usize(self.memberCount, serializer);
    sse_encode_opt_String(self.parentOrgId, serializer);
    sse_encode_opt_String(self.networkFourWords, serializer);
    sse_encode_bool(self.isLocalOnly, serializer);
  }

  @protected
  void sse_encode_flutter_entity_type(
      FlutterEntityType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_event(FlutterEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FlutterEvent_NetworkingStarted(address: final address):
        sse_encode_i_32(0, serializer);
        sse_encode_String(address, serializer);
      case FlutterEvent_NetworkingStopped():
        sse_encode_i_32(1, serializer);
      case FlutterEvent_PeerConnected(peerId: final peerId):
        sse_encode_i_32(2, serializer);
        sse_encode_String(peerId, serializer);
      case FlutterEvent_PeerDisconnected(peerId: final peerId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(peerId, serializer);
      case FlutterEvent_EntityCreated(entityId: final entityId):
        sse_encode_i_32(4, serializer);
        sse_encode_String(entityId, serializer);
      case FlutterEvent_EntityUpdated(entityId: final entityId):
        sse_encode_i_32(5, serializer);
        sse_encode_String(entityId, serializer);
      case FlutterEvent_MessageSent(
          messageId: final messageId,
          entityId: final entityId
        ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_String(entityId, serializer);
      case FlutterEvent_MessageReceived(
          messageId: final messageId,
          entityId: final entityId
        ):
        sse_encode_i_32(7, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_String(entityId, serializer);
      case FlutterEvent_InviteCreated(inviteId: final inviteId):
        sse_encode_i_32(8, serializer);
        sse_encode_String(inviteId, serializer);
      case FlutterEvent_InviteAccepted(inviteId: final inviteId):
        sse_encode_i_32(9, serializer);
        sse_encode_String(inviteId, serializer);
      case FlutterEvent_FileWritten(entityId: final entityId, path: final path):
        sse_encode_i_32(10, serializer);
        sse_encode_String(entityId, serializer);
        sse_encode_String(path, serializer);
      case FlutterEvent_FileDeleted(entityId: final entityId, path: final path):
        sse_encode_i_32(11, serializer);
        sse_encode_String(entityId, serializer);
        sse_encode_String(path, serializer);
      case FlutterEvent_Error(code: final code, message: final message):
        sse_encode_i_32(12, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_flutter_network_info(
      FlutterNetworkInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isActive, serializer);
    sse_encode_opt_box_autoadd_u_16(self.boundPort, serializer);
    sse_encode_u_32(self.peerCount, serializer);
    sse_encode_opt_String(self.externalAddress, serializer);
    sse_encode_bool(self.bootstrapConnected, serializer);
  }

  @protected
  void sse_encode_flutter_session_info(
      FlutterSessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.fourWords, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_flutter_user_profile(
      FlutterUserProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fourWords, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
  }

  @protected
  void sse_encode_flutter_vault_info(
      FlutterVaultInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fourWords, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_u_64(self.lastAccessed, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_flutter_entity(
      List<FlutterEntity> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_entity(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flutter_event(
      List<FlutterEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flutter_vault_info(
      List<FlutterVaultInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_vault_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flutter_session_info(
      FlutterSessionInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flutter_session_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CommunitasApiImpl extends RustOpaque implements CommunitasApi {
  // Not to be used by end users
  CommunitasApiImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CommunitasApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: CommunitasRust
        .instance.api.rust_arc_increment_strong_count_CommunitasApi,
    rustArcDecrementStrongCount: CommunitasRust
        .instance.api.rust_arc_decrement_strong_count_CommunitasApi,
    rustArcDecrementStrongCountPtr: CommunitasRust
        .instance.api.rust_arc_decrement_strong_count_CommunitasApiPtr,
  );

  /// Create a new vault with the given identity
  Future<String> authCreateVault(
          {required String fourWords,
          required String displayName,
          required String password}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthCreateVault(
          that: this,
          fourWords: fourWords,
          displayName: displayName,
          password: password);

  /// Delete a vault
  Future<void> authDeleteVault(
          {required String fourWords, required String password}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthDeleteVault(
          that: this, fourWords: fourWords, password: password);

  /// Get the current session info
  Future<FlutterSessionInfo?> authGetCurrentSession() =>
      CommunitasRust.instance.api
          .crateFlutterApiCommunitasApiAuthGetCurrentSession(
        that: this,
      );

  /// List all available vaults
  Future<List<FlutterVaultInfo>> authListVaults() =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthListVaults(
        that: this,
      );

  /// Login to an existing vault
  Future<FlutterSessionInfo> authLogin(
          {required String fourWords, required String password}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthLogin(
          that: this, fourWords: fourWords, password: password);

  /// Logout from the current session
  Future<void> authLogout() =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthLogout(
        that: this,
      );

  /// Check if a vault exists
  Future<bool> authVaultExists({required String fourWords}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiAuthVaultExists(
          that: this, fourWords: fourWords);

  /// Add a member to an entity
  Future<List<FlutterEvent>> entityAddMember(
          {required FlutterEntityType entityType,
          required String entityId,
          required String memberId,
          required String role}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiEntityAddMember(
          that: this,
          entityType: entityType,
          entityId: entityId,
          memberId: memberId,
          role: role);

  /// Create a new entity
  Future<List<FlutterEvent>> entityCreate(
          {required String name,
          required FlutterEntityType entityType,
          String? description,
          String? parentOrgId}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiEntityCreate(
          that: this,
          name: name,
          entityType: entityType,
          description: description,
          parentOrgId: parentOrgId);

  /// Get an entity by ID
  Future<FlutterEntity> entityGet({required String entityId}) => CommunitasRust
      .instance.api
      .crateFlutterApiCommunitasApiEntityGet(that: this, entityId: entityId);

  /// List all entities
  Future<List<FlutterEntity>> entityList() =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiEntityList(
        that: this,
      );

  /// List entities by type
  Future<List<FlutterEntity>> entityListByType(
          {required FlutterEntityType entityType}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiEntityListByType(
          that: this, entityType: entityType);

  /// Remove a member from an entity
  Future<List<FlutterEvent>> entityRemoveMember(
          {required FlutterEntityType entityType,
          required String entityId,
          required String memberId}) =>
      CommunitasRust.instance.api
          .crateFlutterApiCommunitasApiEntityRemoveMember(
              that: this,
              entityType: entityType,
              entityId: entityId,
              memberId: memberId);

  /// Get the current user profile
  Future<FlutterUserProfile> getProfile() =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiGetProfile(
        that: this,
      );

  /// Connect to a peer by four words
  Future<List<FlutterEvent>> gossipConnectToPeer({required String fourWords}) =>
      CommunitasRust.instance.api
          .crateFlutterApiCommunitasApiGossipConnectToPeer(
              that: this, fourWords: fourWords);

  /// Get network information
  Future<FlutterNetworkInfo> gossipGetNetworkInfo() =>
      CommunitasRust.instance.api
          .crateFlutterApiCommunitasApiGossipGetNetworkInfo(
        that: this,
      );

  /// Start the gossip network
  Future<List<FlutterEvent>> gossipStart({int? port}) =>
      CommunitasRust.instance.api
          .crateFlutterApiCommunitasApiGossipStart(that: this, port: port);

  /// Stop the gossip network
  Future<List<FlutterEvent>> gossipStop() =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiGossipStop(
        that: this,
      );

  /// Accept an invite
  Future<List<FlutterEvent>> inviteAccept({required String inviteId}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiInviteAccept(
          that: this, inviteId: inviteId);

  /// Create an invite
  Future<List<FlutterEvent>> inviteCreate(
          {required String recipientId,
          required FlutterEntityType entityType,
          required String entityId,
          required String role,
          String? message}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiInviteCreate(
          that: this,
          recipientId: recipientId,
          entityType: entityType,
          entityId: entityId,
          role: role,
          message: message);

  /// Reject an invite
  Future<List<FlutterEvent>> inviteReject({required String inviteId}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiInviteReject(
          that: this, inviteId: inviteId);

  /// Revoke an invite (sender only)
  Future<List<FlutterEvent>> inviteRevoke({required String inviteId}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiInviteRevoke(
          that: this, inviteId: inviteId);

  /// Send a message to an entity
  Future<List<FlutterEvent>> messageSend(
          {required String entityId,
          required FlutterEntityType entityType,
          required String text,
          String? replyToId}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiMessageSend(
          that: this,
          entityId: entityId,
          entityType: entityType,
          text: text,
          replyToId: replyToId);

  /// Update display name
  Future<List<FlutterEvent>> updateDisplayName({required String displayName}) =>
      CommunitasRust.instance.api.crateFlutterApiCommunitasApiUpdateDisplayName(
          that: this, displayName: displayName);
}
