#!/usr/bin/env bash
# parity-check.sh — generate docs/parity.md by comparing X0xClient method
# usage across the Dioxus and Swift apps.
#
# Output is deterministic: for each client method declared in the Rust
# `communitas-x0x-client::client` surface, we check whether it is called from
# (a) the Dioxus app, (b) the Swift app, or (c) neither. The Swift mirror
# uses camelCase while Rust uses snake_case — we normalise both sides to a
# canonical flat form before comparing.
#
# Fails (exit 1) if any client method is declared but unused in both apps,
# *unless* the method name appears in scripts/parity-exclude.txt.
#
# Usage:
#   scripts/parity-check.sh            # writes docs/parity.md
#   scripts/parity-check.sh --stdout   # prints to stdout
#   scripts/parity-check.sh --json     # prints a JSON summary

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RUST_CLIENT="communitas-x0x-client/src/client.rs"
DIOXUS_SRC="communitas-dioxus/src"
SWIFT_SRC="communitas-apple/Sources/Communitas"
EXCLUDE_FILE="scripts/parity-exclude.txt"
OUT="docs/parity.md"

MODE="file"
for arg in "$@"; do
    case "$arg" in
        --stdout) MODE="stdout" ;;
        --json) MODE="json" ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "Unknown flag: $arg" >&2; exit 2 ;;
    esac
done

# ── 1. Enumerate client methods from Rust ────────────────────────────────
methods="$(grep -oE 'pub async fn [a-zA-Z_][a-zA-Z_0-9]*' "$RUST_CLIENT" \
    | awk '{print $4}' | sort -u)"

# ── 2. Build the exclusion set ───────────────────────────────────────────
exclude=""
if [ -f "$EXCLUDE_FILE" ]; then
    exclude="$(grep -v '^[[:space:]]*$\|^[[:space:]]*#' "$EXCLUDE_FILE" | awk '{print $1}')"
fi
is_excluded() {
    local name="$1"
    printf '%s\n' "$exclude" | grep -qx "$name"
}

# ── 3. Check each method ────────────────────────────────────────────────
snake_to_camel() {
    # foo_bar_baz → fooBarBaz
    echo "$1" | awk 'BEGIN{FS="_";OFS=""}{r=$1;for(i=2;i<=NF;i++)r=r toupper(substr($i,1,1)) substr($i,2);print r}'
}

# Collect call sites. We match both bare `client.foo(` and `.client.foo(`
# (e.g. `appState.client.foo`) because Swift tends to access the client
# through a container state object.
dioxus_calls="$(grep -rEoh "[.[:space:]^]client\.[a-zA-Z_][a-zA-Z_0-9]*\(" "$DIOXUS_SRC" 2>/dev/null | sort -u || true)"
swift_calls="$(grep -rEoh "[.[:space:]^]client\.[a-zA-Z][a-zA-Z0-9]*\(" "$SWIFT_SRC" 2>/dev/null | sort -u || true)"

present_in_dioxus() {
    local snake="$1"
    printf '%s\n' "$dioxus_calls" | grep -q "client\\.${snake}(" && return 0
    return 1
}
present_in_swift() {
    local camel
    camel="$(snake_to_camel "$1")"
    printf '%s\n' "$swift_calls" | grep -q "client\\.${camel}(" && return 0
    return 1
}

both=0
dioxus_only=0
swift_only=0
neither=0
neither_names=()
dioxus_only_names=()
swift_only_names=()

declare -a rows
while IFS= read -r m; do
    if present_in_dioxus "$m"; then D="yes"; else D="no"; fi
    if present_in_swift "$m"; then S="yes"; else S="no"; fi
    if [ "$D" = "yes" ] && [ "$S" = "yes" ]; then
        both=$((both+1))
        status="both"
    elif [ "$D" = "yes" ]; then
        dioxus_only=$((dioxus_only+1))
        dioxus_only_names+=("$m")
        status="dioxus-only"
    elif [ "$S" = "yes" ]; then
        swift_only=$((swift_only+1))
        swift_only_names+=("$m")
        status="swift-only"
    else
        if is_excluded "$m"; then
            status="neither (excluded)"
        else
            neither=$((neither+1))
            neither_names+=("$m")
            status="neither"
        fi
    fi
    rows+=("$m|$D|$S|$status")
done <<< "$methods"

total="$(printf '%s\n' "$methods" | wc -l | tr -d ' ')"
both_pct=$(awk -v b="$both" -v t="$total" 'BEGIN{if(t==0){print 0}else{printf "%.1f", (b/t)*100}}')

# ── 4. Emit ──────────────────────────────────────────────────────────────
write_markdown() {
    cat <<EOF
# Dioxus ↔ Swift parity

_Generated by \`just parity\`. Do not hand-edit._

**Client methods tracked:** ${total}
**In both apps:** ${both} (${both_pct}%)
**Dioxus only:** ${dioxus_only}
**Swift only:** ${swift_only}
**Unused in both (excluding whitelist):** ${neither}

| Method | Dioxus | Swift | Status |
|---|---|---|---|
EOF
    for row in "${rows[@]}"; do
        IFS='|' read -r name d s status <<< "$row"
        echo "| \`$name\` | $d | $s | $status |"
    done
    if [ "${#neither_names[@]}" -gt 0 ]; then
        echo
        echo '## Unused in both (not in whitelist)'
        for n in "${neither_names[@]}"; do echo "- \`$n\`"; done
    fi
    if [ "${#dioxus_only_names[@]}" -gt 0 ]; then
        echo
        echo '## Dioxus-only'
        for n in "${dioxus_only_names[@]}"; do echo "- \`$n\`"; done
    fi
    if [ "${#swift_only_names[@]}" -gt 0 ]; then
        echo
        echo '## Swift-only'
        for n in "${swift_only_names[@]}"; do echo "- \`$n\`"; done
    fi
}

write_json() {
    printf '{\n'
    printf '  "total": %s,\n' "$total"
    printf '  "both": %s,\n' "$both"
    printf '  "dioxus_only": %s,\n' "$dioxus_only"
    printf '  "swift_only": %s,\n' "$swift_only"
    printf '  "neither": %s,\n' "$neither"
    printf '  "both_pct": %s,\n' "$both_pct"
    printf '  "rows": [\n'
    local first=1
    for row in "${rows[@]}"; do
        IFS='|' read -r name d s status <<< "$row"
        if [ $first -eq 1 ]; then first=0; else printf ',\n'; fi
        printf '    {"method":"%s","dioxus":"%s","swift":"%s","status":"%s"}' \
            "$name" "$d" "$s" "$status"
    done
    printf '\n  ]\n}\n'
}

case "$MODE" in
    stdout) write_markdown ;;
    json) write_json ;;
    file)
        mkdir -p docs
        write_markdown > "$OUT"
        echo "Wrote $OUT"
        echo "Both: ${both}/${total} (${both_pct}%)  dioxus-only: ${dioxus_only}  swift-only: ${swift_only}  neither: ${neither}"
        ;;
esac

# Fail when anything is unused in both *and* not excluded.
if [ "$neither" -gt 0 ]; then
    echo "FAIL: ${neither} client methods are unused in both apps and not whitelisted." >&2
    exit 1
fi
