//! Application messages and events for tui-realm component architecture
//!
//! This module defines the message types used for component communication,
//! user events from async/P2P systems, and component identifiers.

use serde::{Deserialize, Serialize};

/// Application messages for inter-component communication
///
/// These messages are generated by components and processed by the Update trait.
/// They represent all possible state changes and user actions in the application.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Msg {
    // === Application Control ===
    /// Request to close the application
    AppClose,
    /// Request to show help screen
    ShowHelp,
    /// Request to toggle theme (dark/light)
    ToggleTheme,

    // === Navigation ===
    /// Navigate back in history
    NavigateBack,
    /// Navigate to dashboard
    NavigateToDashboard,
    /// Navigate to organizations list
    NavigateToOrganizations,
    /// Navigate to projects list
    NavigateToProjects,
    /// Navigate to groups list
    NavigateToGroups,
    /// Navigate to contacts list
    NavigateToContacts,
    /// Navigate to specific channel
    NavigateToChannel(String),
    /// Navigate to specific thread
    NavigateToThread { message_id: String, channel_id: String },
    /// Navigate to network status
    NavigateToNetworkStatus,

    // === Authentication ===
    /// Authentication started
    AuthenticationStarted,
    /// Authentication completed successfully
    AuthenticationSuccess { four_words: String },
    /// Authentication failed
    AuthenticationFailed(String),
    /// Logout requested
    LogoutRequested,

    // === Entity Management ===
    /// Organization created
    OrganizationCreated(String),
    /// Organization selected
    OrganizationSelected(String),
    /// Project created
    ProjectCreated(String),
    /// Project selected
    ProjectSelected(String),
    /// Group created
    GroupCreated(String),
    /// Group selected
    GroupSelected(String),
    /// Contact added
    ContactAdded(String),
    /// Contact selected
    ContactSelected(String),

    // === Messaging ===
    /// Message sent
    MessageSent { channel_id: String, content: String },
    /// Message selected in list
    MessageSelected { message_id: String },
    /// Message edited
    MessageEdited { message_id: String, new_content: String },
    /// Message deleted
    MessageDeleted(String),
    /// Thread created from message
    ThreadCreated { message_id: String, thread_id: String },
    /// Thread opened for viewing
    ThreadOpened { message_id: String },
    /// Reply added to thread
    ReplyAdded { thread_id: String, content: String },
    /// Reaction added to message
    ReactionAdded { message_id: String, emoji: String },
    /// Typing indicator started
    TypingStarted(String), // user_id
    /// Typing indicator stopped
    TypingStopped(String), // user_id

    // === File Operations ===
    /// File uploaded
    FileUploaded { path: String, name: String },
    /// File download started
    FileDownloadStarted(String),
    /// File download completed
    FileDownloadCompleted(String),

    // === Network ===
    /// Network status changed
    NetworkStatusChanged(NetworkStatus),
    /// Peer connected
    PeerConnected { peer_id: String, address: String },
    /// Peer disconnected
    PeerDisconnected(String),

    // === Modal/Dialog ===
    /// Open modal dialog
    OpenModal(ModalType),
    /// Close current modal
    CloseModal,
    /// Modal action confirmed
    ModalConfirmed(ModalType),
    /// Modal action cancelled
    ModalCancelled,

    // === Component Focus ===
    /// Component gained focus
    FocusGained(ComponentId),
    /// Component lost focus
    FocusLost(ComponentId),
    /// Focus next component
    FocusNext,
    /// Focus previous component
    FocusPrevious,

    // === Input/Forms ===
    /// Text input changed
    InputChanged { component: ComponentId, value: String },
    /// Form submitted
    FormSubmitted(ComponentId),
    /// Form validation failed
    FormValidationFailed { component: ComponentId, errors: Vec<String> },

    // === UI State ===
    /// Status message updated
    StatusUpdated(String),
    /// Error occurred
    ErrorOccurred(String),
    /// Success notification
    SuccessNotification(String),
    /// Selection changed in a list component
    SelectionChanged { component: ComponentId, index: usize },
    /// Redraw requested
    RedrawRequested,

    // === No-op ===
    /// No message (used for fallthrough cases)
    None,
}

/// Network connection status
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NetworkStatus {
    /// Disconnected from network
    Disconnected,
    /// Connecting to network
    Connecting,
    /// Connected to network
    Connected,
    /// Connection error
    Error(String),
}

/// Modal dialog types
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ModalType {
    /// Create new organization
    CreateOrganization,
    /// Create new project
    CreateProject,
    /// Create new group
    CreateGroup,
    /// Add contact
    AddContact,
    /// Display QR code for identity
    ShowQRCode(String),
    /// Confirm action
    Confirmation { title: String, message: String },
    /// Error dialog
    Error(String),
    /// Help screen
    Help,
}

/// User events from async/P2P systems
///
/// These events are generated by background tasks, network operations,
/// or other async processes and are injected into the event loop.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UserEvent {
    /// Message received via gossip
    GossipMessageReceived {
        channel_id: String,
        message_id: String,
        sender: String,
        content: String,
        timestamp: i64,
    },

    /// Presence update received
    PresenceUpdate {
        user_id: String,
        status: PresenceStatus,
    },

    /// Network peer connected
    PeerConnected {
        peer_id: String,
        address: String,
    },

    /// Network peer disconnected
    PeerDisconnected {
        peer_id: String,
    },

    /// Network status changed
    NetworkStatusChanged(NetworkStatus),

    /// Storage update completed
    StorageUpdated {
        entity_id: String,
        operation: String,
    },

    /// CRDT sync received
    CRDTSyncReceived {
        entity_id: String,
        update_count: usize,
    },

    /// File transfer progress
    FileTransferProgress {
        file_id: String,
        bytes_transferred: u64,
        total_bytes: u64,
    },

    /// Background task completed
    TaskCompleted {
        task_id: String,
        result: TaskResult,
    },
}

/// User presence status
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PresenceStatus {
    /// User is online
    Online,
    /// User is away
    Away,
    /// User is busy/do not disturb
    Busy,
    /// User is offline
    Offline,
}

/// Task completion result
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskResult {
    /// Task succeeded
    Success(String),
    /// Task failed
    Failed(String),
}

/// Component identifiers for focus management and message routing
///
/// Each interactive component in the application has a unique ID.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ComponentId {
    // === Layout Components ===
    /// Main application container
    Main,
    /// Left sidebar
    Sidebar,
    /// Center content pane
    ContentPane,
    /// Right context panel
    ContextPanel,
    /// Status bar
    StatusBar,

    // === Navigation Components ===
    /// Organization list
    OrganizationList,
    /// Project list
    ProjectList,
    /// Group list
    GroupList,
    /// Contact list
    ContactList,
    /// Channel list
    ChannelList,

    // === Content Components ===
    /// Message list
    MessageList,
    /// Message input
    MessageInput,
    /// Message composer (text input for new messages)
    MessageComposer,
    /// Thread view
    ThreadView,
    /// File browser
    FileBrowser,
    /// Member list
    MemberList,

    // === Modal Components ===
    /// Modal overlay
    ModalOverlay,
    /// QR code display
    QRCodeDisplay,
    /// Form input
    FormInput(u32), // indexed for multiple inputs
    /// Confirmation dialog
    ConfirmationDialog,

    // === Visualization Components ===
    /// Network graph
    NetworkGraph,
    /// Metrics chart
    MetricsChart,
    /// Avatar display
    Avatar(String), // user_id

    // === Input Components ===
    /// Text input field
    TextInput(String), // field name
    /// Autocomplete input
    AutocompleteInput(String),
    /// Multi-select list
    MultiSelect(String),
}

impl ComponentId {
    /// Get a human-readable name for this component
    pub fn name(&self) -> String {
        match self {
            ComponentId::Main => "Main".to_string(),
            ComponentId::Sidebar => "Sidebar".to_string(),
            ComponentId::ContentPane => "Content".to_string(),
            ComponentId::ContextPanel => "Context".to_string(),
            ComponentId::StatusBar => "Status".to_string(),
            ComponentId::OrganizationList => "Organizations".to_string(),
            ComponentId::ProjectList => "Projects".to_string(),
            ComponentId::GroupList => "Groups".to_string(),
            ComponentId::ContactList => "Contacts".to_string(),
            ComponentId::ChannelList => "Channels".to_string(),
            ComponentId::MessageList => "Messages".to_string(),
            ComponentId::MessageInput => "Message Input".to_string(),
            ComponentId::MessageComposer => "Message Composer".to_string(),
            ComponentId::ThreadView => "Thread".to_string(),
            ComponentId::FileBrowser => "Files".to_string(),
            ComponentId::MemberList => "Members".to_string(),
            ComponentId::ModalOverlay => "Modal".to_string(),
            ComponentId::QRCodeDisplay => "QR Code".to_string(),
            ComponentId::FormInput(id) => format!("Form Input {}", id),
            ComponentId::ConfirmationDialog => "Confirmation".to_string(),
            ComponentId::NetworkGraph => "Network Graph".to_string(),
            ComponentId::MetricsChart => "Metrics".to_string(),
            ComponentId::Avatar(user_id) => format!("Avatar: {}", user_id),
            ComponentId::TextInput(name) => format!("Input: {}", name),
            ComponentId::AutocompleteInput(name) => format!("Autocomplete: {}", name),
            ComponentId::MultiSelect(name) => format!("MultiSelect: {}", name),
        }
    }
}
