// SPDX-License-Identifier: MIT OR Apache-2.0

//! Parity proof: every x0x REST endpoint in the `named-groups` category
//! has a corresponding client method.
//!
//! The vendored `tests/fixtures/api-manifest.json` is a copy of the file
//! generated by `X0X_REGEN_MANIFEST=1 cargo test --test api_manifest` in
//! the x0x repo. When x0xd gains a new `/groups/*` endpoint, regenerate
//! the manifest in both repos and add a matching method here — this test
//! is the enforcement.
//!
//! Run: cargo nextest run -p communitas-x0x-client --test parity_manifest

use serde::Deserialize;
use std::collections::BTreeSet;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Manifest {
    endpoints: Vec<Endpoint>,
}

#[derive(Debug, Deserialize)]
struct Endpoint {
    method: String,
    path: String,
    category: String,
}

/// Every (method, path) on `communitas_x0x_client::X0xClient` that
/// targets a named-groups endpoint. Kept in sync with the actual
/// methods defined in `src/client.rs`.
const IMPLEMENTED: &[(&str, &str)] = &[
    // Core CRUD
    ("POST", "/groups"),
    ("GET", "/groups"),
    ("GET", "/groups/:id"),
    ("PATCH", "/groups/:id"),
    ("DELETE", "/groups/:id"),
    // Membership
    ("GET", "/groups/:id/members"),
    ("POST", "/groups/:id/members"),
    ("DELETE", "/groups/:id/members/:agent_id"),
    ("PATCH", "/groups/:id/members/:agent_id/role"),
    ("PUT", "/groups/:id/display-name"),
    // Policy / bans
    ("PATCH", "/groups/:id/policy"),
    ("POST", "/groups/:id/ban/:agent_id"),
    ("DELETE", "/groups/:id/ban/:agent_id"),
    // Join requests
    ("GET", "/groups/:id/requests"),
    ("POST", "/groups/:id/requests"),
    ("POST", "/groups/:id/requests/:request_id/approve"),
    ("POST", "/groups/:id/requests/:request_id/reject"),
    ("DELETE", "/groups/:id/requests/:request_id"),
    // Invite / join
    ("POST", "/groups/:id/invite"),
    ("POST", "/groups/join"),
    // Public messaging
    ("POST", "/groups/:id/send"),
    ("GET", "/groups/:id/messages"),
    // State chain (D.3)
    ("GET", "/groups/:id/state"),
    ("POST", "/groups/:id/state/seal"),
    ("POST", "/groups/:id/state/withdraw"),
    // Discovery (C + C.2)
    ("GET", "/groups/discover"),
    ("GET", "/groups/discover/nearby"),
    ("GET", "/groups/discover/subscriptions"),
    ("POST", "/groups/discover/subscribe"),
    ("DELETE", "/groups/discover/subscribe/:kind/:shard"),
    ("GET", "/groups/cards/:id"),
    ("POST", "/groups/cards/import"),
    // Secure plane (D.2)
    ("POST", "/groups/:id/secure/encrypt"),
    ("POST", "/groups/:id/secure/decrypt"),
    ("POST", "/groups/:id/secure/reseal"),
    ("POST", "/groups/secure/open-envelope"),
];

fn load_manifest() -> Manifest {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/api-manifest.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read vendored manifest {}: {e}\n\
             Regenerate it in the x0x repo with: \
             X0X_REGEN_MANIFEST=1 cargo test --test api_manifest\n\
             then copy x0x/docs/design/api-manifest.json into \
             communitas-x0x-client/tests/fixtures/",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("parse manifest JSON")
}

#[test]
fn every_named_group_endpoint_has_a_client_method() {
    let manifest = load_manifest();
    let implemented: BTreeSet<(String, String)> = IMPLEMENTED
        .iter()
        .map(|(m, p)| (m.to_string(), p.to_string()))
        .collect();

    let mut missing: Vec<String> = manifest
        .endpoints
        .iter()
        .filter(|e| e.category == "named-groups")
        .filter(|e| !implemented.contains(&(e.method.clone(), e.path.clone())))
        .map(|e| format!("  {} {}", e.method, e.path))
        .collect();
    missing.sort();

    assert!(
        missing.is_empty(),
        "\n\nnamed-groups endpoints in the x0x manifest have no \
         communitas-x0x-client method ({} missing):\n{}\n\n\
         Fix: add a method in src/client.rs and register it in \
         tests/parity_manifest.rs::IMPLEMENTED.\n",
        missing.len(),
        missing.join("\n")
    );
}

#[test]
fn every_implemented_entry_exists_in_the_manifest() {
    let manifest = load_manifest();
    let manifest_set: BTreeSet<(String, String)> = manifest
        .endpoints
        .iter()
        .filter(|e| e.category == "named-groups")
        .map(|e| (e.method.clone(), e.path.clone()))
        .collect();

    let mut stale: Vec<String> = IMPLEMENTED
        .iter()
        .filter(|(m, p)| !manifest_set.contains(&(m.to_string(), p.to_string())))
        .map(|(m, p)| format!("  {m} {p}"))
        .collect();
    stale.sort();

    assert!(
        stale.is_empty(),
        "\n\nparity_manifest::IMPLEMENTED has entries not present in the \
         x0x manifest ({} stale):\n{}\n\n\
         Either x0x removed an endpoint — regenerate the vendored \
         manifest and drop these entries — or the method is mislabeled.\n",
        stale.len(),
        stale.join("\n")
    );
}
